# ==============================================================
# Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2023.2 (64-bit)
# Tool Version Limit: 2023.10
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
# 
# ==============================================================
proc sc_sim_check {ret err logfile} {
	if {$::AESL_AUTOSIM::gDebug == 1} {
		puts stdout "[debug_prompt arg check_sim.tcl] start...";
	}
    set errfile "err.log"
    if {[file exists $errfile] && [file size $errfile] != 0} {
        set fl [open $errfile r]
        while {[gets $fl line] >= 0} {
            if {[string first "AESL_mErrNo = " $line] == 0} {
                set mismatch_num [string range $line [string length "AESL_mErrNo = "] end]
                if {$mismatch_num != 0} {
                    ::AP::printMsg ERR COSIM 403 COSIM_403_986 ${mismatch_num}
                    break
                }
            }
        }
    }
    if {$ret || $err != ""} {
        if { [lindex $::errorCode 0] eq "CHILDSTATUS"} {
            set status [lindex $::errorCode 2]
            if {$status != ""} {
                ::AP::printMsg ERR COSIM 404 COSIM_404_987 $status
            } else {
                ::AP::printMsg ERR COSIM 405 COSIM_405_988
            }
        } else {
            ::AP::printMsg ERR COSIM 405 COSIM_405_989
        }
    }
    if {[file exists $logfile]} {
        set cmdret [catch {eval exec "grep \"Error:\" $logfile"} err]
        file delete -force $logfile
        if {$cmdret == 0} {
            ::AP::printMsg ERR COSIM 405 COSIM_405_990
        }
    }
	if {$::AESL_AUTOSIM::gDebug == 1} {
		puts stdout "[debug_prompt arg check_sim.tcl] finish...";
	}
}

proc rtl_sim_check {} {
	if {$::AESL_AUTOSIM::gDebug == 1} {
		puts stdout "[debug_prompt arg check_sim.tcl] start...";
	}
    set errfile "err.log"
    if {[file exists $errfile] && [file size $errfile] != 0} {
        set fl [open $errfile r]
        set unmatch_num 0
        while {[gets $fl line] >= 0} {
            if {[string first "unmatched" $line] != -1} {
                set unmatch_num [expr $unmatch_num + 1]
            }
        }
        if {$unmatch_num != 0} {
            ::AP::printMsg ERR COSIM 406 COSIM_406_991 ${unmatch_num}
        }
    }
    if {[file exists ".aesl_error"]} {
        set errfl [open ".aesl_error" r]
        gets $errfl line
        if {$line != 0} {
            ::AP::printMsg ERR COSIM 407 COSIM_407_992 $line
        }
    }
    if {[file exists ".exit.err"]} {
        ::AP::printMsg ERR COSIM 405 COSIM_405_993
    }
	if {$::AESL_AUTOSIM::gDebug == 1} {
		puts stdout "[debug_prompt arg check_sim.tcl] finish...";
	}
}

proc check_tvin_file {} {
	if {$::AESL_AUTOSIM::gDebug == 1} {
		puts stdout "[debug_prompt arg check_sim.tcl] start...";
	}
    set rtlfilelist {
         "c.myproject.autotvin_layer_normalization_input.dat"
    }
    foreach rtlfile $rtlfilelist {
        if {[file isfile $rtlfile]} {
        } else {
            ::AP::printMsg ERR COSIM 320 COSIM_320_994
            return 1
        }
    }
	if {$::AESL_AUTOSIM::gDebug == 1} {
		puts stdout "[debug_prompt arg check_sim.tcl] finish...";
	}
    return 0
}

proc check_tvout_file {} {
	if {$::AESL_AUTOSIM::gDebug == 1} {
		puts stdout "[debug_prompt arg check_sim.tcl] start...";
	}
    set rtlfilelist {
         "rtl.myproject.autotvout_layer2_out_0.dat"
         "rtl.myproject.autotvout_layer2_out_1.dat"
         "rtl.myproject.autotvout_layer2_out_2.dat"
         "rtl.myproject.autotvout_layer2_out_3.dat"
         "rtl.myproject.autotvout_layer2_out_4.dat"
         "rtl.myproject.autotvout_layer2_out_5.dat"
         "rtl.myproject.autotvout_layer2_out_6.dat"
         "rtl.myproject.autotvout_layer2_out_7.dat"
         "rtl.myproject.autotvout_layer2_out_8.dat"
         "rtl.myproject.autotvout_layer2_out_9.dat"
         "rtl.myproject.autotvout_layer2_out_10.dat"
         "rtl.myproject.autotvout_layer2_out_11.dat"
         "rtl.myproject.autotvout_layer2_out_12.dat"
         "rtl.myproject.autotvout_layer2_out_13.dat"
         "rtl.myproject.autotvout_layer2_out_14.dat"
         "rtl.myproject.autotvout_layer2_out_15.dat"
         "rtl.myproject.autotvout_layer2_out_16.dat"
         "rtl.myproject.autotvout_layer2_out_17.dat"
         "rtl.myproject.autotvout_layer2_out_18.dat"
         "rtl.myproject.autotvout_layer2_out_19.dat"
         "rtl.myproject.autotvout_layer2_out_20.dat"
         "rtl.myproject.autotvout_layer2_out_21.dat"
         "rtl.myproject.autotvout_layer2_out_22.dat"
         "rtl.myproject.autotvout_layer2_out_23.dat"
         "rtl.myproject.autotvout_layer2_out_24.dat"
         "rtl.myproject.autotvout_layer2_out_25.dat"
         "rtl.myproject.autotvout_layer2_out_26.dat"
         "rtl.myproject.autotvout_layer2_out_27.dat"
         "rtl.myproject.autotvout_layer2_out_28.dat"
         "rtl.myproject.autotvout_layer2_out_29.dat"
         "rtl.myproject.autotvout_layer2_out_30.dat"
         "rtl.myproject.autotvout_layer2_out_31.dat"
         "rtl.myproject.autotvout_layer2_out_32.dat"
         "rtl.myproject.autotvout_layer2_out_33.dat"
         "rtl.myproject.autotvout_layer2_out_34.dat"
         "rtl.myproject.autotvout_layer2_out_35.dat"
         "rtl.myproject.autotvout_layer2_out_36.dat"
         "rtl.myproject.autotvout_layer2_out_37.dat"
         "rtl.myproject.autotvout_layer2_out_38.dat"
         "rtl.myproject.autotvout_layer2_out_39.dat"
         "rtl.myproject.autotvout_layer2_out_40.dat"
         "rtl.myproject.autotvout_layer2_out_41.dat"
         "rtl.myproject.autotvout_layer2_out_42.dat"
         "rtl.myproject.autotvout_layer2_out_43.dat"
         "rtl.myproject.autotvout_layer2_out_44.dat"
         "rtl.myproject.autotvout_layer2_out_45.dat"
         "rtl.myproject.autotvout_layer2_out_46.dat"
         "rtl.myproject.autotvout_layer2_out_47.dat"
         "rtl.myproject.autotvout_layer2_out_48.dat"
         "rtl.myproject.autotvout_layer2_out_49.dat"
         "rtl.myproject.autotvout_layer2_out_50.dat"
         "rtl.myproject.autotvout_layer2_out_51.dat"
         "rtl.myproject.autotvout_layer2_out_52.dat"
         "rtl.myproject.autotvout_layer2_out_53.dat"
         "rtl.myproject.autotvout_layer2_out_54.dat"
         "rtl.myproject.autotvout_layer2_out_55.dat"
         "rtl.myproject.autotvout_layer2_out_56.dat"
         "rtl.myproject.autotvout_layer2_out_57.dat"
         "rtl.myproject.autotvout_layer2_out_58.dat"
         "rtl.myproject.autotvout_layer2_out_59.dat"
         "rtl.myproject.autotvout_layer2_out_60.dat"
         "rtl.myproject.autotvout_layer2_out_61.dat"
         "rtl.myproject.autotvout_layer2_out_62.dat"
         "rtl.myproject.autotvout_layer2_out_63.dat"
         "rtl.myproject.autotvout_layer2_out_64.dat"
         "rtl.myproject.autotvout_layer2_out_65.dat"
         "rtl.myproject.autotvout_layer2_out_66.dat"
         "rtl.myproject.autotvout_layer2_out_67.dat"
         "rtl.myproject.autotvout_layer2_out_68.dat"
         "rtl.myproject.autotvout_layer2_out_69.dat"
         "rtl.myproject.autotvout_layer2_out_70.dat"
         "rtl.myproject.autotvout_layer2_out_71.dat"
         "rtl.myproject.autotvout_layer2_out_72.dat"
         "rtl.myproject.autotvout_layer2_out_73.dat"
         "rtl.myproject.autotvout_layer2_out_74.dat"
         "rtl.myproject.autotvout_layer2_out_75.dat"
         "rtl.myproject.autotvout_layer2_out_76.dat"
         "rtl.myproject.autotvout_layer2_out_77.dat"
         "rtl.myproject.autotvout_layer2_out_78.dat"
         "rtl.myproject.autotvout_layer2_out_79.dat"
         "rtl.myproject.autotvout_layer2_out_80.dat"
         "rtl.myproject.autotvout_layer2_out_81.dat"
         "rtl.myproject.autotvout_layer2_out_82.dat"
         "rtl.myproject.autotvout_layer2_out_83.dat"
         "rtl.myproject.autotvout_layer2_out_84.dat"
         "rtl.myproject.autotvout_layer2_out_85.dat"
         "rtl.myproject.autotvout_layer2_out_86.dat"
         "rtl.myproject.autotvout_layer2_out_87.dat"
         "rtl.myproject.autotvout_layer2_out_88.dat"
         "rtl.myproject.autotvout_layer2_out_89.dat"
         "rtl.myproject.autotvout_layer2_out_90.dat"
         "rtl.myproject.autotvout_layer2_out_91.dat"
         "rtl.myproject.autotvout_layer2_out_92.dat"
         "rtl.myproject.autotvout_layer2_out_93.dat"
         "rtl.myproject.autotvout_layer2_out_94.dat"
         "rtl.myproject.autotvout_layer2_out_95.dat"
         "rtl.myproject.autotvout_layer2_out_96.dat"
         "rtl.myproject.autotvout_layer2_out_97.dat"
         "rtl.myproject.autotvout_layer2_out_98.dat"
         "rtl.myproject.autotvout_layer2_out_99.dat"
         "rtl.myproject.autotvout_layer2_out_100.dat"
         "rtl.myproject.autotvout_layer2_out_101.dat"
         "rtl.myproject.autotvout_layer2_out_102.dat"
         "rtl.myproject.autotvout_layer2_out_103.dat"
         "rtl.myproject.autotvout_layer2_out_104.dat"
         "rtl.myproject.autotvout_layer2_out_105.dat"
         "rtl.myproject.autotvout_layer2_out_106.dat"
         "rtl.myproject.autotvout_layer2_out_107.dat"
         "rtl.myproject.autotvout_layer2_out_108.dat"
         "rtl.myproject.autotvout_layer2_out_109.dat"
         "rtl.myproject.autotvout_layer2_out_110.dat"
         "rtl.myproject.autotvout_layer2_out_111.dat"
         "rtl.myproject.autotvout_layer2_out_112.dat"
         "rtl.myproject.autotvout_layer2_out_113.dat"
         "rtl.myproject.autotvout_layer2_out_114.dat"
         "rtl.myproject.autotvout_layer2_out_115.dat"
         "rtl.myproject.autotvout_layer2_out_116.dat"
         "rtl.myproject.autotvout_layer2_out_117.dat"
         "rtl.myproject.autotvout_layer2_out_118.dat"
         "rtl.myproject.autotvout_layer2_out_119.dat"
         "rtl.myproject.autotvout_layer2_out_120.dat"
         "rtl.myproject.autotvout_layer2_out_121.dat"
         "rtl.myproject.autotvout_layer2_out_122.dat"
         "rtl.myproject.autotvout_layer2_out_123.dat"
         "rtl.myproject.autotvout_layer2_out_124.dat"
         "rtl.myproject.autotvout_layer2_out_125.dat"
         "rtl.myproject.autotvout_layer2_out_126.dat"
         "rtl.myproject.autotvout_layer2_out_127.dat"
         "rtl.myproject.autotvout_layer2_out_128.dat"
         "rtl.myproject.autotvout_layer2_out_129.dat"
         "rtl.myproject.autotvout_layer2_out_130.dat"
         "rtl.myproject.autotvout_layer2_out_131.dat"
         "rtl.myproject.autotvout_layer2_out_132.dat"
         "rtl.myproject.autotvout_layer2_out_133.dat"
         "rtl.myproject.autotvout_layer2_out_134.dat"
         "rtl.myproject.autotvout_layer2_out_135.dat"
         "rtl.myproject.autotvout_layer2_out_136.dat"
         "rtl.myproject.autotvout_layer2_out_137.dat"
         "rtl.myproject.autotvout_layer2_out_138.dat"
         "rtl.myproject.autotvout_layer2_out_139.dat"
         "rtl.myproject.autotvout_layer2_out_140.dat"
         "rtl.myproject.autotvout_layer2_out_141.dat"
         "rtl.myproject.autotvout_layer2_out_142.dat"
         "rtl.myproject.autotvout_layer2_out_143.dat"
         "rtl.myproject.autotvout_layer2_out_144.dat"
         "rtl.myproject.autotvout_layer2_out_145.dat"
         "rtl.myproject.autotvout_layer2_out_146.dat"
         "rtl.myproject.autotvout_layer2_out_147.dat"
         "rtl.myproject.autotvout_layer2_out_148.dat"
         "rtl.myproject.autotvout_layer2_out_149.dat"
         "rtl.myproject.autotvout_layer2_out_150.dat"
         "rtl.myproject.autotvout_layer2_out_151.dat"
         "rtl.myproject.autotvout_layer2_out_152.dat"
         "rtl.myproject.autotvout_layer2_out_153.dat"
         "rtl.myproject.autotvout_layer2_out_154.dat"
         "rtl.myproject.autotvout_layer2_out_155.dat"
         "rtl.myproject.autotvout_layer2_out_156.dat"
         "rtl.myproject.autotvout_layer2_out_157.dat"
         "rtl.myproject.autotvout_layer2_out_158.dat"
         "rtl.myproject.autotvout_layer2_out_159.dat"
         "rtl.myproject.autotvout_layer2_out_160.dat"
         "rtl.myproject.autotvout_layer2_out_161.dat"
         "rtl.myproject.autotvout_layer2_out_162.dat"
         "rtl.myproject.autotvout_layer2_out_163.dat"
         "rtl.myproject.autotvout_layer2_out_164.dat"
         "rtl.myproject.autotvout_layer2_out_165.dat"
         "rtl.myproject.autotvout_layer2_out_166.dat"
         "rtl.myproject.autotvout_layer2_out_167.dat"
         "rtl.myproject.autotvout_layer2_out_168.dat"
         "rtl.myproject.autotvout_layer2_out_169.dat"
         "rtl.myproject.autotvout_layer2_out_170.dat"
         "rtl.myproject.autotvout_layer2_out_171.dat"
         "rtl.myproject.autotvout_layer2_out_172.dat"
         "rtl.myproject.autotvout_layer2_out_173.dat"
         "rtl.myproject.autotvout_layer2_out_174.dat"
         "rtl.myproject.autotvout_layer2_out_175.dat"
         "rtl.myproject.autotvout_layer2_out_176.dat"
         "rtl.myproject.autotvout_layer2_out_177.dat"
         "rtl.myproject.autotvout_layer2_out_178.dat"
         "rtl.myproject.autotvout_layer2_out_179.dat"
         "rtl.myproject.autotvout_layer2_out_180.dat"
         "rtl.myproject.autotvout_layer2_out_181.dat"
         "rtl.myproject.autotvout_layer2_out_182.dat"
         "rtl.myproject.autotvout_layer2_out_183.dat"
         "rtl.myproject.autotvout_layer2_out_184.dat"
         "rtl.myproject.autotvout_layer2_out_185.dat"
         "rtl.myproject.autotvout_layer2_out_186.dat"
         "rtl.myproject.autotvout_layer2_out_187.dat"
         "rtl.myproject.autotvout_layer2_out_188.dat"
         "rtl.myproject.autotvout_layer2_out_189.dat"
         "rtl.myproject.autotvout_layer2_out_190.dat"
         "rtl.myproject.autotvout_layer2_out_191.dat"
         "rtl.myproject.autotvout_layer2_out_192.dat"
         "rtl.myproject.autotvout_layer2_out_193.dat"
         "rtl.myproject.autotvout_layer2_out_194.dat"
         "rtl.myproject.autotvout_layer2_out_195.dat"
         "rtl.myproject.autotvout_layer2_out_196.dat"
         "rtl.myproject.autotvout_layer2_out_197.dat"
         "rtl.myproject.autotvout_layer2_out_198.dat"
         "rtl.myproject.autotvout_layer2_out_199.dat"
         "rtl.myproject.autotvout_layer2_out_200.dat"
         "rtl.myproject.autotvout_layer2_out_201.dat"
         "rtl.myproject.autotvout_layer2_out_202.dat"
         "rtl.myproject.autotvout_layer2_out_203.dat"
         "rtl.myproject.autotvout_layer2_out_204.dat"
         "rtl.myproject.autotvout_layer2_out_205.dat"
         "rtl.myproject.autotvout_layer2_out_206.dat"
         "rtl.myproject.autotvout_layer2_out_207.dat"
         "rtl.myproject.autotvout_layer2_out_208.dat"
         "rtl.myproject.autotvout_layer2_out_209.dat"
         "rtl.myproject.autotvout_layer2_out_210.dat"
         "rtl.myproject.autotvout_layer2_out_211.dat"
         "rtl.myproject.autotvout_layer2_out_212.dat"
         "rtl.myproject.autotvout_layer2_out_213.dat"
         "rtl.myproject.autotvout_layer2_out_214.dat"
         "rtl.myproject.autotvout_layer2_out_215.dat"
         "rtl.myproject.autotvout_layer2_out_216.dat"
         "rtl.myproject.autotvout_layer2_out_217.dat"
         "rtl.myproject.autotvout_layer2_out_218.dat"
         "rtl.myproject.autotvout_layer2_out_219.dat"
         "rtl.myproject.autotvout_layer2_out_220.dat"
         "rtl.myproject.autotvout_layer2_out_221.dat"
         "rtl.myproject.autotvout_layer2_out_222.dat"
         "rtl.myproject.autotvout_layer2_out_223.dat"
         "rtl.myproject.autotvout_layer2_out_224.dat"
         "rtl.myproject.autotvout_layer2_out_225.dat"
         "rtl.myproject.autotvout_layer2_out_226.dat"
         "rtl.myproject.autotvout_layer2_out_227.dat"
         "rtl.myproject.autotvout_layer2_out_228.dat"
         "rtl.myproject.autotvout_layer2_out_229.dat"
         "rtl.myproject.autotvout_layer2_out_230.dat"
         "rtl.myproject.autotvout_layer2_out_231.dat"
         "rtl.myproject.autotvout_layer2_out_232.dat"
         "rtl.myproject.autotvout_layer2_out_233.dat"
         "rtl.myproject.autotvout_layer2_out_234.dat"
         "rtl.myproject.autotvout_layer2_out_235.dat"
         "rtl.myproject.autotvout_layer2_out_236.dat"
         "rtl.myproject.autotvout_layer2_out_237.dat"
         "rtl.myproject.autotvout_layer2_out_238.dat"
         "rtl.myproject.autotvout_layer2_out_239.dat"
         "rtl.myproject.autotvout_layer2_out_240.dat"
         "rtl.myproject.autotvout_layer2_out_241.dat"
         "rtl.myproject.autotvout_layer2_out_242.dat"
         "rtl.myproject.autotvout_layer2_out_243.dat"
         "rtl.myproject.autotvout_layer2_out_244.dat"
         "rtl.myproject.autotvout_layer2_out_245.dat"
         "rtl.myproject.autotvout_layer2_out_246.dat"
         "rtl.myproject.autotvout_layer2_out_247.dat"
         "rtl.myproject.autotvout_layer2_out_248.dat"
         "rtl.myproject.autotvout_layer2_out_249.dat"
         "rtl.myproject.autotvout_layer2_out_250.dat"
         "rtl.myproject.autotvout_layer2_out_251.dat"
         "rtl.myproject.autotvout_layer2_out_252.dat"
         "rtl.myproject.autotvout_layer2_out_253.dat"
         "rtl.myproject.autotvout_layer2_out_254.dat"
         "rtl.myproject.autotvout_layer2_out_255.dat"
         "rtl.myproject.autotvout_layer2_out_256.dat"
         "rtl.myproject.autotvout_layer2_out_257.dat"
         "rtl.myproject.autotvout_layer2_out_258.dat"
         "rtl.myproject.autotvout_layer2_out_259.dat"
         "rtl.myproject.autotvout_layer2_out_260.dat"
         "rtl.myproject.autotvout_layer2_out_261.dat"
         "rtl.myproject.autotvout_layer2_out_262.dat"
         "rtl.myproject.autotvout_layer2_out_263.dat"
         "rtl.myproject.autotvout_layer2_out_264.dat"
         "rtl.myproject.autotvout_layer2_out_265.dat"
         "rtl.myproject.autotvout_layer2_out_266.dat"
         "rtl.myproject.autotvout_layer2_out_267.dat"
         "rtl.myproject.autotvout_layer2_out_268.dat"
         "rtl.myproject.autotvout_layer2_out_269.dat"
         "rtl.myproject.autotvout_layer2_out_270.dat"
         "rtl.myproject.autotvout_layer2_out_271.dat"
         "rtl.myproject.autotvout_layer2_out_272.dat"
         "rtl.myproject.autotvout_layer2_out_273.dat"
         "rtl.myproject.autotvout_layer2_out_274.dat"
         "rtl.myproject.autotvout_layer2_out_275.dat"
         "rtl.myproject.autotvout_layer2_out_276.dat"
         "rtl.myproject.autotvout_layer2_out_277.dat"
         "rtl.myproject.autotvout_layer2_out_278.dat"
         "rtl.myproject.autotvout_layer2_out_279.dat"
         "rtl.myproject.autotvout_layer2_out_280.dat"
         "rtl.myproject.autotvout_layer2_out_281.dat"
         "rtl.myproject.autotvout_layer2_out_282.dat"
         "rtl.myproject.autotvout_layer2_out_283.dat"
         "rtl.myproject.autotvout_layer2_out_284.dat"
         "rtl.myproject.autotvout_layer2_out_285.dat"
         "rtl.myproject.autotvout_layer2_out_286.dat"
         "rtl.myproject.autotvout_layer2_out_287.dat"
         "rtl.myproject.autotvout_layer2_out_288.dat"
         "rtl.myproject.autotvout_layer2_out_289.dat"
         "rtl.myproject.autotvout_layer2_out_290.dat"
         "rtl.myproject.autotvout_layer2_out_291.dat"
         "rtl.myproject.autotvout_layer2_out_292.dat"
         "rtl.myproject.autotvout_layer2_out_293.dat"
         "rtl.myproject.autotvout_layer2_out_294.dat"
         "rtl.myproject.autotvout_layer2_out_295.dat"
         "rtl.myproject.autotvout_layer2_out_296.dat"
         "rtl.myproject.autotvout_layer2_out_297.dat"
         "rtl.myproject.autotvout_layer2_out_298.dat"
         "rtl.myproject.autotvout_layer2_out_299.dat"
         "rtl.myproject.autotvout_layer2_out_300.dat"
         "rtl.myproject.autotvout_layer2_out_301.dat"
         "rtl.myproject.autotvout_layer2_out_302.dat"
         "rtl.myproject.autotvout_layer2_out_303.dat"
         "rtl.myproject.autotvout_layer2_out_304.dat"
         "rtl.myproject.autotvout_layer2_out_305.dat"
         "rtl.myproject.autotvout_layer2_out_306.dat"
         "rtl.myproject.autotvout_layer2_out_307.dat"
         "rtl.myproject.autotvout_layer2_out_308.dat"
         "rtl.myproject.autotvout_layer2_out_309.dat"
         "rtl.myproject.autotvout_layer2_out_310.dat"
         "rtl.myproject.autotvout_layer2_out_311.dat"
         "rtl.myproject.autotvout_layer2_out_312.dat"
         "rtl.myproject.autotvout_layer2_out_313.dat"
         "rtl.myproject.autotvout_layer2_out_314.dat"
         "rtl.myproject.autotvout_layer2_out_315.dat"
         "rtl.myproject.autotvout_layer2_out_316.dat"
         "rtl.myproject.autotvout_layer2_out_317.dat"
         "rtl.myproject.autotvout_layer2_out_318.dat"
         "rtl.myproject.autotvout_layer2_out_319.dat"
         "rtl.myproject.autotvout_layer2_out_320.dat"
         "rtl.myproject.autotvout_layer2_out_321.dat"
         "rtl.myproject.autotvout_layer2_out_322.dat"
         "rtl.myproject.autotvout_layer2_out_323.dat"
         "rtl.myproject.autotvout_layer2_out_324.dat"
         "rtl.myproject.autotvout_layer2_out_325.dat"
         "rtl.myproject.autotvout_layer2_out_326.dat"
         "rtl.myproject.autotvout_layer2_out_327.dat"
         "rtl.myproject.autotvout_layer2_out_328.dat"
         "rtl.myproject.autotvout_layer2_out_329.dat"
         "rtl.myproject.autotvout_layer2_out_330.dat"
         "rtl.myproject.autotvout_layer2_out_331.dat"
         "rtl.myproject.autotvout_layer2_out_332.dat"
         "rtl.myproject.autotvout_layer2_out_333.dat"
         "rtl.myproject.autotvout_layer2_out_334.dat"
         "rtl.myproject.autotvout_layer2_out_335.dat"
         "rtl.myproject.autotvout_layer2_out_336.dat"
         "rtl.myproject.autotvout_layer2_out_337.dat"
         "rtl.myproject.autotvout_layer2_out_338.dat"
         "rtl.myproject.autotvout_layer2_out_339.dat"
         "rtl.myproject.autotvout_layer2_out_340.dat"
         "rtl.myproject.autotvout_layer2_out_341.dat"
         "rtl.myproject.autotvout_layer2_out_342.dat"
         "rtl.myproject.autotvout_layer2_out_343.dat"
         "rtl.myproject.autotvout_layer2_out_344.dat"
         "rtl.myproject.autotvout_layer2_out_345.dat"
         "rtl.myproject.autotvout_layer2_out_346.dat"
         "rtl.myproject.autotvout_layer2_out_347.dat"
         "rtl.myproject.autotvout_layer2_out_348.dat"
         "rtl.myproject.autotvout_layer2_out_349.dat"
         "rtl.myproject.autotvout_layer2_out_350.dat"
         "rtl.myproject.autotvout_layer2_out_351.dat"
         "rtl.myproject.autotvout_layer2_out_352.dat"
         "rtl.myproject.autotvout_layer2_out_353.dat"
         "rtl.myproject.autotvout_layer2_out_354.dat"
         "rtl.myproject.autotvout_layer2_out_355.dat"
         "rtl.myproject.autotvout_layer2_out_356.dat"
         "rtl.myproject.autotvout_layer2_out_357.dat"
         "rtl.myproject.autotvout_layer2_out_358.dat"
         "rtl.myproject.autotvout_layer2_out_359.dat"
         "rtl.myproject.autotvout_layer2_out_360.dat"
         "rtl.myproject.autotvout_layer2_out_361.dat"
         "rtl.myproject.autotvout_layer2_out_362.dat"
         "rtl.myproject.autotvout_layer2_out_363.dat"
         "rtl.myproject.autotvout_layer2_out_364.dat"
         "rtl.myproject.autotvout_layer2_out_365.dat"
         "rtl.myproject.autotvout_layer2_out_366.dat"
         "rtl.myproject.autotvout_layer2_out_367.dat"
         "rtl.myproject.autotvout_layer2_out_368.dat"
         "rtl.myproject.autotvout_layer2_out_369.dat"
         "rtl.myproject.autotvout_layer2_out_370.dat"
         "rtl.myproject.autotvout_layer2_out_371.dat"
         "rtl.myproject.autotvout_layer2_out_372.dat"
         "rtl.myproject.autotvout_layer2_out_373.dat"
         "rtl.myproject.autotvout_layer2_out_374.dat"
         "rtl.myproject.autotvout_layer2_out_375.dat"
         "rtl.myproject.autotvout_layer2_out_376.dat"
         "rtl.myproject.autotvout_layer2_out_377.dat"
         "rtl.myproject.autotvout_layer2_out_378.dat"
         "rtl.myproject.autotvout_layer2_out_379.dat"
         "rtl.myproject.autotvout_layer2_out_380.dat"
         "rtl.myproject.autotvout_layer2_out_381.dat"
         "rtl.myproject.autotvout_layer2_out_382.dat"
         "rtl.myproject.autotvout_layer2_out_383.dat"
         "rtl.myproject.autotvout_layer2_out_384.dat"
         "rtl.myproject.autotvout_layer2_out_385.dat"
         "rtl.myproject.autotvout_layer2_out_386.dat"
         "rtl.myproject.autotvout_layer2_out_387.dat"
         "rtl.myproject.autotvout_layer2_out_388.dat"
         "rtl.myproject.autotvout_layer2_out_389.dat"
         "rtl.myproject.autotvout_layer2_out_390.dat"
         "rtl.myproject.autotvout_layer2_out_391.dat"
         "rtl.myproject.autotvout_layer2_out_392.dat"
         "rtl.myproject.autotvout_layer2_out_393.dat"
         "rtl.myproject.autotvout_layer2_out_394.dat"
         "rtl.myproject.autotvout_layer2_out_395.dat"
         "rtl.myproject.autotvout_layer2_out_396.dat"
         "rtl.myproject.autotvout_layer2_out_397.dat"
         "rtl.myproject.autotvout_layer2_out_398.dat"
         "rtl.myproject.autotvout_layer2_out_399.dat"
         "rtl.myproject.autotvout_layer2_out_400.dat"
         "rtl.myproject.autotvout_layer2_out_401.dat"
         "rtl.myproject.autotvout_layer2_out_402.dat"
         "rtl.myproject.autotvout_layer2_out_403.dat"
         "rtl.myproject.autotvout_layer2_out_404.dat"
         "rtl.myproject.autotvout_layer2_out_405.dat"
         "rtl.myproject.autotvout_layer2_out_406.dat"
         "rtl.myproject.autotvout_layer2_out_407.dat"
         "rtl.myproject.autotvout_layer2_out_408.dat"
         "rtl.myproject.autotvout_layer2_out_409.dat"
         "rtl.myproject.autotvout_layer2_out_410.dat"
         "rtl.myproject.autotvout_layer2_out_411.dat"
         "rtl.myproject.autotvout_layer2_out_412.dat"
         "rtl.myproject.autotvout_layer2_out_413.dat"
         "rtl.myproject.autotvout_layer2_out_414.dat"
         "rtl.myproject.autotvout_layer2_out_415.dat"
         "rtl.myproject.autotvout_layer2_out_416.dat"
         "rtl.myproject.autotvout_layer2_out_417.dat"
         "rtl.myproject.autotvout_layer2_out_418.dat"
         "rtl.myproject.autotvout_layer2_out_419.dat"
         "rtl.myproject.autotvout_layer2_out_420.dat"
         "rtl.myproject.autotvout_layer2_out_421.dat"
         "rtl.myproject.autotvout_layer2_out_422.dat"
         "rtl.myproject.autotvout_layer2_out_423.dat"
         "rtl.myproject.autotvout_layer2_out_424.dat"
         "rtl.myproject.autotvout_layer2_out_425.dat"
         "rtl.myproject.autotvout_layer2_out_426.dat"
         "rtl.myproject.autotvout_layer2_out_427.dat"
         "rtl.myproject.autotvout_layer2_out_428.dat"
         "rtl.myproject.autotvout_layer2_out_429.dat"
         "rtl.myproject.autotvout_layer2_out_430.dat"
         "rtl.myproject.autotvout_layer2_out_431.dat"
         "rtl.myproject.autotvout_layer2_out_432.dat"
         "rtl.myproject.autotvout_layer2_out_433.dat"
         "rtl.myproject.autotvout_layer2_out_434.dat"
         "rtl.myproject.autotvout_layer2_out_435.dat"
         "rtl.myproject.autotvout_layer2_out_436.dat"
         "rtl.myproject.autotvout_layer2_out_437.dat"
         "rtl.myproject.autotvout_layer2_out_438.dat"
         "rtl.myproject.autotvout_layer2_out_439.dat"
         "rtl.myproject.autotvout_layer2_out_440.dat"
         "rtl.myproject.autotvout_layer2_out_441.dat"
         "rtl.myproject.autotvout_layer2_out_442.dat"
         "rtl.myproject.autotvout_layer2_out_443.dat"
         "rtl.myproject.autotvout_layer2_out_444.dat"
         "rtl.myproject.autotvout_layer2_out_445.dat"
         "rtl.myproject.autotvout_layer2_out_446.dat"
         "rtl.myproject.autotvout_layer2_out_447.dat"
         "rtl.myproject.autotvout_layer2_out_448.dat"
         "rtl.myproject.autotvout_layer2_out_449.dat"
         "rtl.myproject.autotvout_layer2_out_450.dat"
         "rtl.myproject.autotvout_layer2_out_451.dat"
         "rtl.myproject.autotvout_layer2_out_452.dat"
         "rtl.myproject.autotvout_layer2_out_453.dat"
         "rtl.myproject.autotvout_layer2_out_454.dat"
         "rtl.myproject.autotvout_layer2_out_455.dat"
         "rtl.myproject.autotvout_layer2_out_456.dat"
         "rtl.myproject.autotvout_layer2_out_457.dat"
         "rtl.myproject.autotvout_layer2_out_458.dat"
         "rtl.myproject.autotvout_layer2_out_459.dat"
         "rtl.myproject.autotvout_layer2_out_460.dat"
         "rtl.myproject.autotvout_layer2_out_461.dat"
         "rtl.myproject.autotvout_layer2_out_462.dat"
         "rtl.myproject.autotvout_layer2_out_463.dat"
         "rtl.myproject.autotvout_layer2_out_464.dat"
         "rtl.myproject.autotvout_layer2_out_465.dat"
         "rtl.myproject.autotvout_layer2_out_466.dat"
         "rtl.myproject.autotvout_layer2_out_467.dat"
         "rtl.myproject.autotvout_layer2_out_468.dat"
         "rtl.myproject.autotvout_layer2_out_469.dat"
         "rtl.myproject.autotvout_layer2_out_470.dat"
         "rtl.myproject.autotvout_layer2_out_471.dat"
         "rtl.myproject.autotvout_layer2_out_472.dat"
         "rtl.myproject.autotvout_layer2_out_473.dat"
         "rtl.myproject.autotvout_layer2_out_474.dat"
         "rtl.myproject.autotvout_layer2_out_475.dat"
         "rtl.myproject.autotvout_layer2_out_476.dat"
         "rtl.myproject.autotvout_layer2_out_477.dat"
         "rtl.myproject.autotvout_layer2_out_478.dat"
         "rtl.myproject.autotvout_layer2_out_479.dat"
    }
    foreach rtlfile $rtlfilelist {
        if {[file isfile $rtlfile]} {
        } else {
            ::AP::printMsg ERR COSIM 303 COSIM_303_996
            return 1
        }
    }
	if {$::AESL_AUTOSIM::gDebug == 1} {
		puts stdout "[debug_prompt arg check_sim.tcl] finish...";
	}
    return 0
}
