Backend: Vivado
ClockPeriod: 5
ClockUncertainty: 12.5%
HLSConfig:
  LayerName:
    key:
      Precision:
        result: ap_fixed<16,6>
      Trace: false
    mha:
      Precision:
        accum: ap_fixed<16,6>
        attention_output_bias: ap_fixed<16,6>
        attention_output_weight: ap_fixed<16,6>
        key_bias: ap_fixed<16,6>
        key_weight: ap_fixed<16,6>
        query_bias: ap_fixed<16,6>
        query_weight: ap_fixed<16,6>
        result: ap_fixed<16,6>
        value_bias: ap_fixed<16,6>
        value_weight: ap_fixed<16,6>
      ReuseFactor: 1
      Trace: false
    query:
      Precision:
        result: ap_fixed<16,6>
      Trace: false
    value:
      Precision:
        result: ap_fixed<16,6>
      Trace: false
  Model:
    ChannelsLastConversion: 'off'
    Precision: ap_fixed<16,6>
    ReuseFactor: 1
    Strategy: Latency
    TransposeOutputs: false
IOType: io_parallel
InputData: /home/rian/A3D3/transformer-synthesis/data/pytorch_mha_data.dat
InputShape:
- !!python/tuple
  - 100
  - 16
- !!python/tuple
  - 100
  - 16
- !!python/tuple
  - 100
  - 16
OutputDir: /home/rian/A3D3/transformer-synthesis/hls4ml_projects/pytorch_mha_Vivado
OutputPredictions: /home/rian/A3D3/transformer-synthesis/data/pytorch_mha_predictions.dat
Part: xcvu13p-flga2577-2-e
ProjectName: myproject
PytorchModel: !!python/object:__main__.MultiHeadAttentionModel
  _backward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _backward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _buffers: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks_always_called: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _is_full_backward_hook: null
  _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _modules: !!python/object/apply:collections.OrderedDict
  - - - mha
      - !!python/object:torch.nn.modules.activation.MultiheadAttention
        _backward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _backward_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _buffers: !!python/object/apply:collections.OrderedDict
        - []
        _forward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _forward_hooks_always_called: !!python/object/apply:collections.OrderedDict
        - []
        _forward_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
        - []
        _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _forward_pre_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
        - []
        _is_full_backward_hook: null
        _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _modules: !!python/object/apply:collections.OrderedDict
        - - - out_proj
            - !!python/object:torch.nn.modules.linear.NonDynamicallyQuantizableLinear
              _backward_hooks: !!python/object/apply:collections.OrderedDict
              - []
              _backward_pre_hooks: !!python/object/apply:collections.OrderedDict
              - []
              _buffers: !!python/object/apply:collections.OrderedDict
              - []
              _forward_hooks: !!python/object/apply:collections.OrderedDict
              - []
              _forward_hooks_always_called: !!python/object/apply:collections.OrderedDict
              - []
              _forward_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
              - []
              _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
              - []
              _forward_pre_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
              - []
              _is_full_backward_hook: null
              _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
              - []
              _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
              - []
              _modules: !!python/object/apply:collections.OrderedDict
              - []
              _non_persistent_buffers_set: !!set {}
              _parameters: !!python/object/apply:collections.OrderedDict
              - - - weight
                  - !!python/object/apply:torch._utils._rebuild_parameter
                    - !!python/object/apply:torch._utils._rebuild_tensor_v2
                      - !!python/object/apply:torch.storage._load_from_bytes
                        - !!binary |
                          gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                          AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                          aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                          Z2UKcQFYCQAAADI1NzU5MTI4MHECWAMAAABjcHVxA00AAU50cQRRLoACXXEAWAkAAAAyNTc1OTEy
                          ODBxAWEuAAEAAAAAAACwNKA8HMfUvWDaiTx4Yfm9FExRPmpVF74OYCi+5i0+PmjfEL5gIvW9wHd6
                          vrblGz4MRko+8N4oPpC6Ar3Usrq90lYXPoRK7D12owG+xmppvlCtCr6AZas9PLrRvXItYr6GKjS+
                          WM5UvkBdqLuAIA68SmA9PmCLwT1AjEW+VGeUPSrrST4ETBA+1o8qPnpmSr7wF2E9CIQrvhz+5T14
                          7FK9SO0/viC9Dz562jY+dKQQviSRhL2Mn4M9RG+lvSw/oD0w4U09jotDPu6QFL7Yn449kB1gvqSy
                          Vr4Uu3W+utEAvlgxtD3mH0a+8KNPPdgYM77IsMa9QFTHO5SsPz7S/mS+qiA+vnAL2zy0ja+9AHWj
                          vCizdr3YP169TiJkvhD/mjzAe3Y8cADTPCy05D3IVWg9snI2vgjaML7YyVS+1o0avrBbj7xwHMo8
                          CCzqPXwr0T1QoaE8kldKvuqWAj5s68C9GPlVvtD8E72GVXS+GDy5PcrjFL7AN5q8QoJMPtCDJj4Q
                          24E98MSYPAinXL3cCwo+8KBavnLIcD5CjB0+ALZmPkARubyMKBE+YpAFPnzu+z3a/3E+2AVSvQw7
                          +736bjE+rHE2vlqLfD4YVL697nURPuSjSb64uFW+IM54PdzQ1T0oJN+9ZLxkvrpdeb6ca0g+zN1g
                          vs7LFb7EWH0+QNGLvKLMTj5wXv49ZGw3PnBLnDyyJ38+4PbHvHwrjz3IgkM+7nQxvhQdXz4wOlO+
                          ANCKOOhWcb4AsKC9KPxDvhxIpb3sLWe+ED7WvAa1Dz6auF4+sKHGvDDkgjycjSm+POc8vq6XKL7g
                          DIe8ILvDvChAE75+7GK+oO8pvuDtSj6U5OY9qkYPvgByRDs0zz2+gPufPcRRXT587qW9BGV0PgTp
                          /D0QQF29vBoxPoCaA7s4gjE+UJySvXDaqrwUJ/s94Gbivf7nDr4clOo98HQUPuCxtbywm769NAki
                          vnhtOz7gEnM8JG8MvkJYUb74sGc9kFQ5PU43fT4YLTO+aEFqvlTp0D2atGM+nLUmvpCCGL2E5XM+
                          AOaYu4D4Jrv0GWk+QNG9vRD9+DzI7UM+jgRiPqicX73YshA9ctV6PjLeS74Ay2A85MQUvpLxI77C
                          u2W+aBK5vZrDLr4ydjI+JFk0vgD0pDyQcT29bsUAPhyLST4w64q8uqs3PmjOcz3Q9GO+tNo3vipL
                          ET4ALXi+nHyMvbjIAD4UoLW9dEqmPXg2Cr7gmbq8+v5XvgADJ76q3Aa+0u0IvhwBQj7u9Cu+qLhi
                          PvY9Ez4MK2y+wObKPMRb/r0gx7s9GK48PcKGd76AZhE8YHwovXY6aL6Kemg+tDVivtBQpD3Ur0G+
                          eKl+Pqb9UT7g3/u9
                      - 0
                      - !!python/tuple
                        - 16
                        - 16
                      - !!python/tuple
                        - 16
                        - 1
                      - false
                      - !!python/object/apply:collections.OrderedDict
                        - []
                    - true
                    - !!python/object/apply:collections.OrderedDict
                      - []
                - - bias
                  - !!python/object/apply:torch._utils._rebuild_parameter
                    - !!python/object/apply:torch._utils._rebuild_tensor_v2
                      - !!python/object/apply:torch.storage._load_from_bytes
                        - !!binary |
                          gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                          AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                          aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                          Z2UKcQFYCQAAADI1ODg0NTcyOHECWAMAAABjcHVxA0sQTnRxBFEugAJdcQBYCQAAADI1ODg0NTcy
                          OHEBYS4QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
                          AAAAAAAAAAAAAAAAAAAAAAAAAAA=
                      - 0
                      - !!python/tuple
                        - 16
                      - !!python/tuple
                        - 1
                      - false
                      - !!python/object/apply:collections.OrderedDict
                        - []
                    - true
                    - !!python/object/apply:collections.OrderedDict
                      - []
              _state_dict_hooks: !!python/object/apply:collections.OrderedDict
              - []
              _state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
              - []
              in_features: 16
              out_features: 16
              training: false
        _non_persistent_buffers_set: !!set {}
        _parameters: !!python/object/apply:collections.OrderedDict
        - - - in_proj_weight
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYCQAAADI2MDQ3OTYzMnECWAMAAABjcHVxA00AA050cQRRLoACXXEAWAkAAAAyNjA0Nzk2
                    MzJxAWEuAAMAAAAAAADpOXs+CXWVPmDUOL6vrLi7SfrqvbGCDr7X1l8+BnsyPeshD7sJzQS+h5qr
                    vahzaj5giZq+9nKgvCQ8l750Xz++VE1VPp0yIr57Qiq+68MOPJG85D3VJ0G+sLIOPuf8Sz43Wuu9
                    We26vSYlAr78f4c+fhFCPtFAqT1g/VG+V+STvnYYHrwG4QU+aitgPGoaUT4UHk2+HVUBPneflb4j
                    e4S9NDgTvp+ngT1+6Co+kA/+Pd6rej6Wj5k+Hif2vSvlib6pD4o+2nS1vQl9I76iapc+FKKMPhCN
                    bj7q8kc9jyWZvV/QjD76i2Q9vfd9PCAwij7igJW+KO4UPkcvE7x054K9PwaYvn50kL7LlVq9aeN1
                    va+Xb74ac4C8xgWZPejWej7M1Ao9m25mvCqjTT6ZXJ+9kZUZPTTsgT6W3ZC+CZt3PlhYc743opa+
                    Qp8VPssmBr4I9sU8YaAIvQuLPD7e0oW+MVgqvdb70T0LlSS+JTaLvdvP3j1anRa+U/MaPreiiD09
                    Rxg+eoPYvaGL8T2OeLY9GKVhPTpC+7wkCWI+n2BxvjEmUr47K1w+O/pdPnS1Eb470CC+chl9vszI
                    vL2H3g0+V5UIPoJ7Xz27WdU94ueEPly//71QQEm+NwiKPjgK2z3iVJ28ltsEvd9ac76Wa0U+cViX
                    vqEeQL63mDq+vKRoPorxkj5OyYe9diygPcSwdr5MoKa9mVeJvvHmgL5VqI2+ENpCPlB/OD5qrou+
                    GimNvq5/nD4L4Ie+vcssPgkj7Dz/Zhe+kL1qPmdoiL7vRz69wFOmPdotV70bYkY+BLECvjRYAbrO
                    5oM+WxJpvVCyobwyBy8+sCVSPTefPz4bZ+o9XFofPpwn6jti6HG9+tCBvhVNRz5efwe+RbcnvN/R
                    cb6RyIg96F93vhhrfL54+IK+0uGTvYHpqbx1BDo+/lY3vgPiKr4IMsG8lzVTPrDIdDvI1da7930n
                    PtxmFL73W0i+HlRkvsPEWr4qP2Q9MdOFvhsIXD4ILIK+nyU8PqizMT4gjuo9rTmlPeD/j75RD4m9
                    efKYPoL/Ub7uVQg+7wHCPfpLoL3uOcq9vZYUPn0UZr4hoC8+uAAAPkXMg75iANs9O1apPJ9Kjb6Q
                    gBc+7uVGvuNHXD5ArIE9xkxqPXEp8z2tYAs+6ShrPh4Hpby+D3g+jDZxPmY/jD63w2O+sx9zPIGk
                    Zj7vGiW+2HAZvtQjBj5nWpK9mrJVPRTUCL53tL+9jYB5vVTLFD7X7Ae8FWVFPgS1Nb7MR+q9/lxv
                    vlZwOT0WkL89uNcqPVljjT7J4Vu+uLhfviiq3rzC3fw9nhdKvh/Qej7Q0n46wtlNPoRHFz4qMwC+
                    ipFqvqIblr1ZZjO+66MZPovUib5Q2Hg+AYl/PhFJR754uSK+onePPeUFdjukmy8+P98mPpWZrL3V
                    gV0++hksvpSqHT2IfI+91o1RPr8QMj50m4099eNdPvDNmT7fotm7t7EBPi7ohDzBkog9O1Ukvns3
                    Mz1lPIk+Z6uTPqsKPzwtfR2+ySVvvA2zVT4FC5s+W45WPrlOkT7uQx29k4pSvaEPmj6LiYa+9AMu
                    voRNYb47H5Q+ir5PPqwxmT067Vs+/qK1Pe/1g75lvIY+vYSMvukcaL57AT2+4opavWjElb7uQYO+
                    OZaSPmYqGb0yqv283h+gPXLGmL5eEAo+a0AavmuwcT63Ftu92Jh3vnfUk77wAWs+99i0PSjq2zxa
                    LGK+dbVnvg+hfT5u3xA+Mhw7PhofOz0m6EY80JWXvahPE72O9a69fPhSPlzAhb798kQ+rbzUvb0D
                    bD6MkX2+ysYoPuRlUz77oUE9Y8jYPSlCZr5PeXa+nVxHvhr9c740ZMq9iTokPlrVgL48h5g+q0C1
                    vaq9EL2LuYu+CS9rvq79gr7f6Jg+7WJWvUp2CbyNfYK+u10OPuixzbq3n9+9HvoxPY8Pir4QX9q9
                    KuF6Ph4gaz3HvSc9HmFAPqLDwj1IGIg+VwjovXXwCr4ZoSW+cHWKPi0KAb4GB4O+DITlvUxKc76J
                    qRg99TscPT21U75GTXI+99hOPmYmdL4JLjQ8eiSAPjtlP77gUyW+x3XBvKSigL4M0UC9bjL8u4jX
                    oT1PBBU+4n5vvRRnQT6jbx6+nriCPqkYxb2+W0g9vfbYvaxOlb7MNpi+3jgbPlajOz15Ej6+2NdI
                    vvnpPb78Dlm+ZzF3Pvl1fj6+24C+ES5ivt7lgz7JY+09Oq+YPnQ+mT4WWHO+rcp3PhMshb20b869
                    pPOAvUeTkz5uHGG+en0lvshDp72Q/Og94otQvsG3Hr364wG83ZebvUl/iL7TEoa+UCSROrrhYT4q
                    /7y88+GRPg+8er4Glhc+Dz+YvEK6QT5hpAK+oe+OPBhKpT2eyNI9UImWvqQaF75atU2+yqE6Pqla
                    vzyMJFO9OqeSPrsfr7141IS9HHORvikRkb4UcIM+Z1qFviJicj7KFDw+PX+Sve6rOD5eaiM+3Xsv
                    PqA1Mr691Vu+2ucZvp+6FT6FRJM9t2EzPvp5xL02Jro7zn5qPmGxXL5WMfQ99+tDvsRpCD5Fm4o9
                    oAE/vn5hSbxoCag9j8Acvg8h3L0RQHC+3qsuvliWJz7llZu+nlnGu+bx3L1/KgK+rMOQvsItMD7H
                    tJs8U6i8vTMCgz5m3ko+CEQpPl7AIz41rmc+PN8evueuhb65EUg+baAzPoLJj7612rC9yZpBvSt8
                    3j1PUw29IPpBPQzXhD5O/Fa+dheMPaO5Gz1Hhdi99FFBPPqdhbz8dSQ8SL/DPBB7Mj3qIfo94FOT
                    Ps3zSL04nxi++PbcPXs5Gj4xYsa9ooFzvnvtOL7UC5a+GNNYvqrzDD5DUoA+6w9Vvk7HOD7Dos49
                    hyY7vSoUfr5vl6I97JSbPm+FND6I34G+F8pVPt71iD4JVeS98ciNvSj8Xj6KQ1I6Cn+SvvY2Dz4S
                    Mxq+s2UPvfKEzrx1/34+Nu9PviiJmDyxoyS+9xEJPo4kTT49rFi8K3SXPs6NMD70fF69ygEsPelF
                    SjzF7ZU+dxOcPjFHT77BDzu+/MSTPd0kTr4EaZI+B1mIPpjMfLwg4CG9MTZnPhixGj2ylku+HNTb
                    uwQVmL1Evl0+8H+EPtBrjjzLdpY+9AxqPtrGMb5Fey4+hmqmPGzkU74RXpa+sDkOPh2nBD7QK9q9
                    DDA2PRt1Db3TsOE9JfPivFwT4j2blbQ9+yBzPi67yjxSAd29s2HtuwEzfD5EjQ6+0khqPvGHOb7V
                    XQQ+76LQvfjKmD6HzB++KQeaPlk1fT1U2eA9qhHGO4yhHT2oOHY+qo2TPqvcLz0wGiy+jwnDPDf8
                    lL54AZA+vhuXPgp+Az39Iy2+zjglPkNfdr6PhpW8o4TEvWaWhj76vhe++zbdOrPBJT4oeCc+ode4
                    PQN26L1SY8Y9Yrs9Ps/Glz5XDH++fx1Yvk3uYD4Usek9IKlqvhwzoz0WPCW9weQ2vlUrOr5hDpi+
                    MzCOvjXSiD6Dvp69fQWNPtqcO75jwzG8/ud1PrwGo72MLou+kqJMPiejGr7wHgW+LbzQPTibGj4E
                    H9M9LeyBvnORXj6GUNM9Ck2FvkeVSD59yoe+ZNNrviGCkrzHX3K+r0SvvZ/SFj5pPCG+m6AyvjJv
                    rL32fUy+mr70PZaFFz6iyH6+1i7UvQhDCb7dkYO9micovZypc77FDSs++EJ3vrITUb7CA4+8Bjcc
                    vmxeSD5Vjjc+tl1XvspExT30NFw+wkoSPuKV4zz2yxq9vA9QvXTvpb0u/FC+q2CTPmy4eT5bgjw9
                    K8SOPsjglb6QTQG+3VvYvEwLlL4zS3083TSCvl4ZYz4G2vg7xsavvadR7Dxklp+9tQz4PfR/Ir22
                    qoO+6wxhPB5eST6j95S+S9x6PvPnSz57sBe+VrkNvpjgh7435yG+h10OvrQ2wz29sBm+pnAQvhSX
                    ybo/0zo+OQcLvqrPz707frc9pyZmvPKdFb1y/3i+gzSSPccVjj1gTlm+B2WKPncH4z26uhE9Fznp
                    ukJzVj5Aowe+SIQpvpcWcD4sZWw9E8ZxPqBbbr1VZYE9GgmyveKrjr6bxrs9EwHGPQlh4L36efK8
                    8EmOvsWVH74=
                - 0
                - !!python/tuple
                  - 48
                  - 16
                - !!python/tuple
                  - 16
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - true
              - !!python/object/apply:collections.OrderedDict
                - []
          - - q_proj_weight
            - null
          - - k_proj_weight
            - null
          - - v_proj_weight
            - null
          - - in_proj_bias
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYCQAAADI1ODg5NjY1NnECWAMAAABjcHVxA0swTnRxBFEugAJdcQBYCQAAADI1ODg5NjY1
                    NnEBYS4wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
                    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
                    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
                    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==
                - 0
                - !!python/tuple
                  - 48
                - !!python/tuple
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - true
              - !!python/object/apply:collections.OrderedDict
                - []
        _qkv_same_embed_dim: true
        _state_dict_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        add_zero_attn: false
        batch_first: true
        bias_k: null
        bias_v: null
        dropout: 0.0
        embed_dim: 16
        head_dim: 2
        kdim: 16
        num_heads: 8
        training: false
        vdim: 16
  _non_persistent_buffers_set: !!set {}
  _parameters: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  training: false
Stamp: eB8ffce6
Version: 1.0.0
WriterConfig:
  Namespace: null
  WriteTar: false
  WriteWeightsTxt: true
