Backend: Vivado
ClockPeriod: 5
ClockUncertainty: 12.5%
HLSConfig:
  LayerName:
    key:
      Precision:
        result: ap_fixed<16,6>
      Trace: false
    mha:
      Precision:
        accum: ap_fixed<16,6>
        attention_output_bias: ap_fixed<16,6>
        attention_output_weight: ap_fixed<16,6>
        key_bias: ap_fixed<16,6>
        key_weight: ap_fixed<16,6>
        query_bias: ap_fixed<16,6>
        query_weight: ap_fixed<16,6>
        result: ap_fixed<16,6>
        value_bias: ap_fixed<16,6>
        value_weight: ap_fixed<16,6>
      ReuseFactor: 1
      Trace: false
    query:
      Precision:
        result: ap_fixed<16,6>
      Trace: false
    value:
      Precision:
        result: ap_fixed<16,6>
      Trace: false
  Model:
    ChannelsLastConversion: 'off'
    Precision: ap_fixed<16,6>
    ReuseFactor: 1
    Strategy: Latency
    TransposeOutputs: false
IOType: io_parallel
InputData: /home/rian/A3D3/transformer-synthesis/data/pytorch_mha_data.dat
InputShape:
- !!python/tuple
  - 100
  - 16
- !!python/tuple
  - 100
  - 16
- !!python/tuple
  - 100
  - 16
OutputDir: /home/rian/A3D3/transformer-synthesis/hls4ml_projects/pytorch_mha_Vivado
OutputPredictions: /home/rian/A3D3/transformer-synthesis/data/pytorch_mha_predictions.dat
Part: xcvu13p-flga2577-2-e
ProjectName: myproject
PytorchModel: !!python/object:__main__.MultiHeadAttentionModel
  _backward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _backward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _buffers: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks_always_called: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _is_full_backward_hook: null
  _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _modules: !!python/object/apply:collections.OrderedDict
  - - - mha
      - !!python/object:torch.nn.modules.activation.MultiheadAttention
        _backward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _backward_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _buffers: !!python/object/apply:collections.OrderedDict
        - []
        _forward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _forward_hooks_always_called: !!python/object/apply:collections.OrderedDict
        - []
        _forward_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
        - []
        _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _forward_pre_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
        - []
        _is_full_backward_hook: null
        _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _modules: !!python/object/apply:collections.OrderedDict
        - - - out_proj
            - !!python/object:torch.nn.modules.linear.NonDynamicallyQuantizableLinear
              _backward_hooks: !!python/object/apply:collections.OrderedDict
              - []
              _backward_pre_hooks: !!python/object/apply:collections.OrderedDict
              - []
              _buffers: !!python/object/apply:collections.OrderedDict
              - []
              _forward_hooks: !!python/object/apply:collections.OrderedDict
              - []
              _forward_hooks_always_called: !!python/object/apply:collections.OrderedDict
              - []
              _forward_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
              - []
              _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
              - []
              _forward_pre_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
              - []
              _is_full_backward_hook: null
              _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
              - []
              _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
              - []
              _modules: !!python/object/apply:collections.OrderedDict
              - []
              _non_persistent_buffers_set: !!set {}
              _parameters: !!python/object/apply:collections.OrderedDict
              - - - weight
                  - !!python/object/apply:torch._utils._rebuild_parameter
                    - !!python/object/apply:torch._utils._rebuild_tensor_v2
                      - !!python/object/apply:torch.storage._load_from_bytes
                        - !!binary |
                          gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                          AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                          aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                          Z2UKcQFYCQAAADI1NjkzNTc2MHECWAMAAABjcHVxA00AAU50cQRRLoACXXEAWAkAAAAyNTY5MzU3
                          NjBxAWEuAAEAAAAAAAAI17a9tuo5PrQqLz5q/nQ+WGMwvXClC75IY9m9DLsLPhAh0zxWA30+AODK
                          OaBIBD0oFrk9pmhmPsCs8L0gWte9YN7rPMhuJb1uFV6+sgwjPtS6JD7YfS0+UsBzPviNlz3A2eU8
                          2D9BPYSRQj4gkd+9wHsHvVCtJL42Y1y+LjIcvjKmb76KVTk+sNl/PoyJIb7eumi+/jQLvm5Zfj5g
                          L+k9UN4wPRbJRT6UmXq+PM7LPZhDQT30lEm+JDMMPtT4+L0kcjW+1MbOPbjY772QPgo+eiNOvhSm
                          R74Ej5O9mHcRPvTvKb4AIFU71E8KPiAWWD3wO+Q8Ckw9PrQwN76S2R++JqguPkCrcD32yH0+pmli
                          vjSb5L2qJkK+yONWPWZyar5I6QI90AsPPmAyBTx+P3s+6hk4vpBkCr6kDHY+IrADPvxHlT1w5ig9
                          /mpMvoAJEz68mo49xulEPkRqoz1YhD6+APo3vZiJMz4Eha09kIhivihxEL3IhQS+GtR5vjxuMT7w
                          yAY+HHZfvoQAH74Ahlk7huVCPiTjMD7kQbu9WIwVPXAEWL6oqNm9VDkEvvZAdj6qlX6+wFrMvRD/
                          NL5gQXc8Jq8Gvhw8br7E9aG9GDELPfp/Qr4kXSK+7lV0PsRTML7Aqh48YAYGvkCk0LzCrxe+eNuF
                          vWgzQT6A9q47iMYwvjgpjj1A/6a9pok/PjI/Mj78F3i+Qr92vhoKbL6ykVa+uHxvPhhVor0wuX89
                          BIQhPiBrZL4kFEQ+2vJAvsyRPb5ABOe9UNbEvE70KL5sQjW+sKcKPbhl/T08wl0+8A7xPATYM76+
                          NW++quI4vgxcxr2I/ze+iBWCvXxt6b0APMU7kLXBPMDjVT6o2eU9xNKUvZRyOz44W0m+aJMtPhBo
                          pz3gRNe8gI62vMC8Pj5wnYa9hInqPTh+eL1IsgW9PGEzPrpyL77AcaE8imwXPgAMKzrAfee7QtUG
                          vngjDj3o2TA+yslDvuYqUj5Q6Q8+sJccPRQbLD6IhOw9HJTqPUAgajyi5GI+rnQbvgZmRD5AXEe9
                          5NdQPuzC9r2AZ1a9XOh0viSzlj2U8l4+kA6QPUp6dT40IEC++MoOvU6kLD7AkDi8gMw2vu5jc754
                          LOI9wpdQPj4vbL6EJlS+HHR6PpZvAT6iDkI+8DtrvpSv4T3guZC9cGQ0vpqYDT5QOau9SBJTvaBx
                          jzxoy1e+kIpmPvrqJz74iA89bGIhPhY2Jz5mjEI+mOE5PczYI768m0E+OCkWvVylyD2u/3u+JE8W
                          PrSQ4j0U7v09ci1LPlCNdj2yxBC+mFcTPvhlLr2I9My9MsACPuAyKT20B2i+tOBavg4LHb4EV7k9
                          TCxgvkSaVL7IEgU9
                      - 0
                      - !!python/tuple
                        - 16
                        - 16
                      - !!python/tuple
                        - 16
                        - 1
                      - false
                      - !!python/object/apply:collections.OrderedDict
                        - []
                    - true
                    - !!python/object/apply:collections.OrderedDict
                      - []
                - - bias
                  - !!python/object/apply:torch._utils._rebuild_parameter
                    - !!python/object/apply:torch._utils._rebuild_tensor_v2
                      - !!python/object/apply:torch.storage._load_from_bytes
                        - !!binary |
                          gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                          AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                          aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                          Z2UKcQFYCQAAADI1Njk2NDYyNHECWAMAAABjcHVxA0sQTnRxBFEugAJdcQBYCQAAADI1Njk2NDYy
                          NHEBYS4QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
                          AAAAAAAAAAAAAAAAAAAAAAAAAAA=
                      - 0
                      - !!python/tuple
                        - 16
                      - !!python/tuple
                        - 1
                      - false
                      - !!python/object/apply:collections.OrderedDict
                        - []
                    - true
                    - !!python/object/apply:collections.OrderedDict
                      - []
              _state_dict_hooks: !!python/object/apply:collections.OrderedDict
              - []
              _state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
              - []
              in_features: 16
              out_features: 16
              training: false
        _non_persistent_buffers_set: !!set {}
        _parameters: !!python/object/apply:collections.OrderedDict
        - - - in_proj_weight
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYCQAAADI1Nzg0NDYyNHECWAMAAABjcHVxA00AA050cQRRLoACXXEAWAkAAAAyNTc4NDQ2
                    MjRxAWEuAAMAAAAAAACqpSu+1Nx5PljguzzM4Zc+IfGLvmWZhz7yWO69Xll2PvV7cr5tqga+QP4r
                    PsiG5T3w8j6+DRJoPnyWmD7n8uG9844rvmiZWL0fgpu+H7woPvWYiD0/lgE+Lx6KPkSrXj5TGPq9
                    RBGRvguIQj7WSPa921K0vH1geD5aXQO96rogPiF4qD3PYSu9Z/XkvXo2GD5JOW8+jYqSPfETFjyn
                    82O96KNEPqZOP76QsFy841rBvR3fpz0CE4a+8P8yPjZyj74v2UW+7a1JPmrReL1q7he9GM59PToN
                    G74ZOG4+41ppPjgcEj6OVxs+T+LCPYl9qb1lYou+dnMRvrP8p73jJKg7R8KTviU3hL0ayYS7wqM0
                    vmE8xj2zlDs+xMgAvlZXNT5f1PU8V5txvnG5C72arlm+DIeTvruFGb5LH4q+qifmPVn4iz5xK5q+
                    9VqDvpdiVz2/WFo8gD5yPhyTjbyDu0U9lmwHvoGOMr0oVyI+NmXVvPJPAr71now+pVAavcOBIT7X
                    1ve9Ith+PsifRr6c1io9DDi6PcgI7DyGcni+qqzkvdGhaj2osxi+EHVKPTeTa749+029AUYCvgTo
                    4z2CbF890Ri8vUchvD0y6nq7Q2AGvhwDJb5wsRk+na50vi0Slj6hNOc8+GQ0Posg+zxz43U+ymV0
                    vmxHe75SF2S9rrnAPd5vkb6ZyWQ8O8WTvMKKPj15elq+dj2HPvNG3L2lK8u9S/fcvbDRET7oEvC9
                    iCHjvaH7YD6fJZC9w05mvcgxnL7tACO+gYWiO7OUPz4roB6+5LTzPTaik73gsRO+9yIAvmp/iz67
                    Mpy+IhcIviHuFD46gHO9Vm1zPltAEDwvUwg9XA8APIAQMz71Czo+rFxgPuCxib7C4Iw+Vtd3PaV0
                    0D0t5JG+FeAVPQ7pQ77U3sI9YSOEvDWc5r31cVQ+vSsbPp/xdD61P5o+70pRPnkSCr5UVpg8fBc1
                    PoxxEz5gGEw+0LvnPVfvcD6BHIM+UvwbPptMq7x0sRI+0niAvYNZWr64UBY9D6vTvUhhKD2om20+
                    L/aLvqH93j3wa1U+vZuavtvOkj79TpW9s9UYPprqlb7olXc+CItJvkNrjD6rXRy+bH5pvnVnnD6U
                    aTK+l/9Dvi3iPz6wHIE95ueKPhr1Qz5JIpU+GIY4vjgZUL7vBog+PNCOPih4jL3b6Nm9YblIPoar
                    Sr6nlhG+a/3cPb46FL7TeLy6ryqMPiBhoLpdnIU+yJKxPIyEH770LyU902c/vmm6YL7+WAc9oHdk
                    PlY/4r3pvIo+mvXEvfAdor022Lm8ocejvaTwPz4bpKg8u0NWveL7Hr13bbM9TQWQvqz8971PbT++
                    IpGtPdHHdb5eaVk+PXU7viApFb6sKeS9BslOPkSsWb6Uz8g9jbpvvt8ZWj4obIA+g3doPoprdz6r
                    qNE9ZGiTvtxFmj4nzjE+qvvZvNK7hL5r2Wq+oGxMPfpqnL1JRD28UoukvRoekT6L1we+YOnhO3HM
                    Tj5M94K9SjGJPstABT4xqIW+f2iqu5weKL462DG+DkQiPtieij7dwHo+ptKVPLsBQD7qn5u+kOmS
                    vmu0gr48IUm9OaYBPglq7j2c+H2+E80lvmw4Cr6y+GY+U95rvsN8Q71cx7K9Xx57vgRZw7yTnxg+
                    znv1OxlZvL1pQM+9EO2Xvlorgr5XweM9lmq0PdnVuL2Ef++9Ish0PixbOT0glJE+uzGGPc17iTvs
                    exS+gjsAvi1iUL3t+I0+8TWWPqHHob1+YJC+9FmWvkXglj6VEYY9pSt8PqejPD19nIY+Fqsxvn+E
                    nb2+mJa+soVqPo+EjD7Fini++o9FvsESkrzyJb48IrycPnFhmz5t6pa8B+hQvnhGQb1qHam9aF0n
                    PulQp70nnYm+GnqHPrgVvL3pGS29BPiLPQtMgb7ShK49biRmPYSkPL7PLZ89SbmFPcdmjD7NxJa+
                    BtIOPk5QbD7TIoU+JX1bPvCETL5T9Ic+eiFXPtJV4DttL02+CUtyvu71aD7wJe09jyGdPQZ4Cr41
                    61k+sHQWPmRFF77PoJE+sjKvPN74hr4O6Gg+QaHcPWaFIL61Myw+dySQvrnHND6K8pi9pp0YPjnt
                    Grwcc848QpptvtDtSr3WH8c9stZ0Pctilz16eyE+jCkRvoB3eT76QtO8yD+RPo1/lL7IeTi+5gTu
                    PQNphT4dNJk+5FBaPgDUgb7UZDk+tN1/Pp2WKr6PRzm+sJCbPpPbcrzO1/i94ioRPq5yNj3+1LO9
                    dsAIvg6rRj6kIjI+cCowPWxiXL6TzGQ+Arj3vS4pKT7PiTc9nqeOPdfRN73DNes9JtuJPhJgiL4l
                    rpO+TDaFvsAqkD2OgDS8r12sPcbvXT5EpzQ+5Yz3u1aHyj2fQ8c9M3xOvidhzTwhnH++S28hvn3/
                    /T3S/Im9G4qKPqOzQz4/Tgm+fFPJvKyfOr59goc+SzSCvTMvi77OR5O+TGfsvVFyAz6RbgI9S07r
                    veOImT4LICc+W5v8PY/04D26Ute9WL4APbw/jr68IhQ++gdovQWokL1wso89BltgPvRdm75HNrU8
                    6RNCPhJ9x72UZ3g+oV+xPUMwLb37qY2+OYCivUu3A74nGe+87JQsPhlGK77GkZM+/3WQPkv5Jj6J
                    qwA+WuOFvu1hY77tUG++ElCDPXKZ672egYU+iKDkPb9ufb4Mpxs+dyAOPokLVb5OdWq+J2gYvtTS
                    lL0BvYA9bH45vsCarj3WvUK+WGLCPX3GNz41DGo9ysmSvmeyQb0PZhy+B5Y9Plk7Ur57mHM+vf++
                    PSQt072KpH2+lgzivasjOr43jyW+NaRVPoD4Sj4tARG+gX+LPpl4ij7jt+c9i0wNvhe33r0hJig+
                    yqpNPpTLerv6y5C88pjQvWCLYTq4LIg+t++IPsnR9b08GR0+P6FfPhne6rv5HkC+3lKZPu7vTL7j
                    Vd89qaV6vstaJr3ISji93VuCvh7bZL7reSs7hoTdvAJBDz4/YUy+NtjUPa/JXT2vbxq8vXKCPV9K
                    jb5Ayny+4k9UPeJ2Bj6/9uy9q5huvYrfG74J/3S9SE3BPfarV77DH+g9BRguvu9A+j0BcYI+Fv8Z
                    vSD7N77eUIQ+JCwWvt1YGr6V+8k8LzlQvVGuXT2IXgQ+7b0avi8ji77AKZG+cxSMvgfiZb0c0yA+
                    k4lbPi+flb7XS5Q+1jYnPhJZJ76bwUY+lRu7vRRWW75K3349KvQoPpwQjL2K2pK8iag+Oqxd170J
                    vCu+lb+DPu1bZz6SHWW9Fuv1PQ5/N76F45O+PlnxvMMCUr7CHIU+Ywr/PG00L76uM3u+fRSQvvuo
                    GL7TVAC+2FDFvKbA373Smsy9aMeRPnRtW75Dgla+o0OEvn/LvDumjXK9MUf8vQnMLb6srdg9+/sO
                    Ppw5Pr6AoJg+wYBMPl3Qgb3lkvq98OuOPlnfG74gGEo+KsJ7PnHscD6qpby99tjxPTA1KD5OFoe+
                    ct2VPvBHtb0xKVY+mCeJviPXgb2ccJC+bqSOvsAHqz0zP949h9GIPi0LdL6Gk24+Pz8PvquNhr4U
                    7t29XvuJPYNjAT5iwIE+QMPZPU1TVj7pe8Q9dfV1vrPkir2gzd07IyF4PtQSbj2/3FI94YBkPMu1
                    aD6V62A97QeKPtj+Wj6lpog+B4Sgva2PcL6jeTk91RhLvUelez3MMQW+vzCJvkunqbu9X5Y+LDNa
                    vnk3Vb2pgk+9n0dHvuChlr56njk+n+0xPjC2pD187GA+YngBPmZ1lb5lS2s+mmG7PZf72bxJe5e+
                    7tI+Pjmdh77YLJs+0ICMvsf5Jj6SUXS+OsYRPiz+gD7Qwho+32WHPS++gL56mpg+czkyPqsV/r2i
                    IS8+GFgpPkzFCb40sna+HdqXPdGcMr7+Pp29KjFGvujMXD53y0w92h+qPVCsmj6ax4k99fNjvp8m
                    hr5OHwg+ppJ8vqJvLb4p2LC9VEV/vtF1gj3UoH49cUqpPW+EojzG/809n2aVvVuYWr27/Jc9iNZc
                    vRtyYr71VWm+ZZPMPUEejz4Iqso7EIp3PWWnPb4Tt4s+3F5VvXgehD5GKEQ+1851PlWx5L1PumI9
                    jpRuvr2wyzg=
                - 0
                - !!python/tuple
                  - 48
                  - 16
                - !!python/tuple
                  - 16
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - true
              - !!python/object/apply:collections.OrderedDict
                - []
          - - q_proj_weight
            - null
          - - k_proj_weight
            - null
          - - v_proj_weight
            - null
          - - in_proj_bias
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYCQAAADI1ODUzMDc4NHECWAMAAABjcHVxA0swTnRxBFEugAJdcQBYCQAAADI1ODUzMDc4
                    NHEBYS4wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
                    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
                    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
                    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==
                - 0
                - !!python/tuple
                  - 48
                - !!python/tuple
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - true
              - !!python/object/apply:collections.OrderedDict
                - []
        _qkv_same_embed_dim: true
        _state_dict_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        add_zero_attn: false
        batch_first: true
        bias_k: null
        bias_v: null
        dropout: 0.0
        embed_dim: 16
        head_dim: 2
        kdim: 16
        num_heads: 8
        training: false
        vdim: 16
  _non_persistent_buffers_set: !!set {}
  _parameters: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  training: false
Stamp: EE8508fC
Version: 1.0.0
WriterConfig:
  Namespace: null
  WriteTar: false
  WriteWeightsTxt: true
