// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config3_2_s (
        ap_clk,
        ap_rst,
        data_0_val,
        data_1_val,
        data_2_val,
        data_3_val,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [15:0] data_0_val;
input  [15:0] data_1_val;
input  [15:0] data_2_val;
input  [15:0] data_3_val;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;
input   ap_ce;

reg[15:0] ap_return_0;
reg[15:0] ap_return_1;
reg[15:0] ap_return_2;
reg[15:0] ap_return_3;

reg   [15:0] trunc_ln_reg_512;
wire    ap_block_pp0_stage0_11001;
reg   [14:0] trunc_ln63_1_reg_517;
reg   [15:0] trunc_ln63_2_reg_522;
reg   [15:0] trunc_ln63_3_reg_527;
reg   [13:0] trunc_ln63_4_reg_532;
reg   [15:0] trunc_ln63_5_reg_537;
reg   [15:0] trunc_ln63_6_reg_542;
reg   [15:0] trunc_ln63_7_reg_547;
reg   [15:0] trunc_ln63_8_reg_552;
reg   [14:0] trunc_ln63_9_reg_557;
reg   [15:0] trunc_ln63_s_reg_562;
reg   [15:0] trunc_ln63_10_reg_567;
reg   [14:0] trunc_ln63_11_reg_572;
reg   [15:0] trunc_ln63_12_reg_577;
reg   [15:0] trunc_ln63_13_reg_582;
reg   [14:0] trunc_ln63_14_reg_587;
wire    ap_block_pp0_stage0;
wire  signed [15:0] sext_ln74_1_fu_102_p0;
wire  signed [15:0] mul_ln78_fu_106_p0;
wire  signed [25:0] sext_ln74_1_fu_102_p1;
wire  signed [9:0] mul_ln78_fu_106_p1;
wire   [25:0] mul_ln78_fu_106_p2;
wire   [8:0] mul_ln78_1_fu_122_p1;
wire   [24:0] mul_ln78_1_fu_122_p2;
wire  signed [15:0] mul_ln78_2_fu_138_p0;
wire   [9:0] mul_ln78_2_fu_138_p1;
wire   [25:0] mul_ln78_2_fu_138_p2;
wire  signed [15:0] mul_ln78_3_fu_154_p0;
wire  signed [9:0] mul_ln78_3_fu_154_p1;
wire   [25:0] mul_ln78_3_fu_154_p2;
wire  signed [15:0] sext_ln74_2_fu_170_p0;
wire  signed [15:0] shl_ln_fu_174_p1;
wire   [22:0] shl_ln_fu_174_p3;
wire  signed [23:0] sext_ln78_fu_182_p1;
wire  signed [15:0] shl_ln78_1_fu_192_p1;
wire   [16:0] shl_ln78_1_fu_192_p3;
wire   [23:0] sub_ln78_fu_186_p2;
wire  signed [23:0] sext_ln78_598_fu_200_p1;
wire   [23:0] sub_ln78_1_fu_204_p2;
wire  signed [15:0] mul_ln78_4_fu_220_p0;
wire  signed [25:0] sext_ln74_2_fu_170_p1;
wire   [9:0] mul_ln78_4_fu_220_p1;
wire   [25:0] mul_ln78_4_fu_220_p2;
wire  signed [15:0] mul_ln63_fu_236_p0;
wire  signed [10:0] mul_ln63_fu_236_p1;
wire   [25:0] mul_ln63_fu_236_p2;
wire  signed [15:0] mul_ln63_1_fu_252_p0;
wire  signed [10:0] mul_ln63_1_fu_252_p1;
wire   [25:0] mul_ln63_1_fu_252_p2;
wire  signed [15:0] sext_ln74_3_fu_268_p0;
wire  signed [15:0] mul_ln63_2_fu_276_p0;
wire  signed [25:0] sext_ln74_3_fu_268_p1;
wire  signed [10:0] mul_ln63_2_fu_276_p1;
wire   [25:0] mul_ln63_2_fu_276_p2;
wire   [8:0] mul_ln78_5_fu_292_p1;
wire   [24:0] mul_ln78_5_fu_292_p2;
wire  signed [15:0] mul_ln78_6_fu_308_p0;
wire   [9:0] mul_ln78_6_fu_308_p1;
wire   [25:0] mul_ln78_6_fu_308_p2;
wire  signed [15:0] mul_ln63_3_fu_324_p0;
wire  signed [10:0] mul_ln63_3_fu_324_p1;
wire   [25:0] mul_ln63_3_fu_324_p2;
wire  signed [15:0] sext_ln63_3_fu_340_p0;
wire  signed [15:0] sext_ln74_5_fu_344_p0;
wire  signed [15:0] mul_ln78_7_fu_348_p0;
wire  signed [24:0] sext_ln74_5_fu_344_p1;
wire   [8:0] mul_ln78_7_fu_348_p1;
wire   [24:0] mul_ln78_7_fu_348_p2;
wire  signed [15:0] mul_ln78_8_fu_364_p0;
wire  signed [25:0] sext_ln63_3_fu_340_p1;
wire  signed [9:0] mul_ln78_8_fu_364_p1;
wire   [25:0] mul_ln78_8_fu_364_p2;
wire  signed [15:0] mul_ln63_4_fu_380_p0;
wire   [10:0] mul_ln63_4_fu_380_p1;
wire   [25:0] mul_ln63_4_fu_380_p2;
wire  signed [15:0] mul_ln78_9_fu_396_p0;
wire   [8:0] mul_ln78_9_fu_396_p1;
wire   [24:0] mul_ln78_9_fu_396_p2;
wire  signed [15:0] sext_ln63_4_fu_421_p1;
wire  signed [15:0] sext_ln63_1_fu_415_p1;
wire   [15:0] add_ln76_1_fu_431_p2;
wire   [15:0] add_ln76_fu_427_p2;
wire  signed [15:0] sext_ln63_fu_412_p1;
wire  signed [15:0] sext_ln63_2_fu_418_p1;
wire   [15:0] add_ln76_4_fu_447_p2;
wire   [15:0] add_ln76_3_fu_443_p2;
wire   [15:0] add_ln76_7_fu_463_p2;
wire   [15:0] add_ln76_6_fu_459_p2;
wire  signed [15:0] sext_ln63_5_fu_424_p1;
wire   [15:0] add_ln76_10_fu_477_p2;
wire   [15:0] add_ln76_9_fu_473_p2;
wire   [15:0] add_ln76_2_fu_437_p2;
wire   [15:0] add_ln76_5_fu_453_p2;
wire   [15:0] add_ln76_8_fu_467_p2;
wire   [15:0] add_ln76_11_fu_482_p2;
reg    ap_ce_reg;
reg   [15:0] ap_return_0_int_reg;
reg   [15:0] ap_return_1_int_reg;
reg   [15:0] ap_return_2_int_reg;
reg   [15:0] ap_return_3_int_reg;

myproject_mul_16s_10s_26_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_1_0_U4945(
    .din0(mul_ln78_fu_106_p0),
    .din1(mul_ln78_fu_106_p1),
    .dout(mul_ln78_fu_106_p2)
);

myproject_mul_16s_9ns_25_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
mul_16s_9ns_25_1_0_U4946(
    .din0(data_0_val),
    .din1(mul_ln78_1_fu_122_p1),
    .dout(mul_ln78_1_fu_122_p2)
);

myproject_mul_16s_10ns_26_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_1_0_U4947(
    .din0(mul_ln78_2_fu_138_p0),
    .din1(mul_ln78_2_fu_138_p1),
    .dout(mul_ln78_2_fu_138_p2)
);

myproject_mul_16s_10s_26_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_1_0_U4948(
    .din0(mul_ln78_3_fu_154_p0),
    .din1(mul_ln78_3_fu_154_p1),
    .dout(mul_ln78_3_fu_154_p2)
);

myproject_mul_16s_10ns_26_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_1_0_U4949(
    .din0(mul_ln78_4_fu_220_p0),
    .din1(mul_ln78_4_fu_220_p1),
    .dout(mul_ln78_4_fu_220_p2)
);

myproject_mul_16s_11s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11s_26_1_1_U4950(
    .din0(mul_ln63_fu_236_p0),
    .din1(mul_ln63_fu_236_p1),
    .dout(mul_ln63_fu_236_p2)
);

myproject_mul_16s_11s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11s_26_1_1_U4951(
    .din0(mul_ln63_1_fu_252_p0),
    .din1(mul_ln63_1_fu_252_p1),
    .dout(mul_ln63_1_fu_252_p2)
);

myproject_mul_16s_11s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11s_26_1_1_U4952(
    .din0(mul_ln63_2_fu_276_p0),
    .din1(mul_ln63_2_fu_276_p1),
    .dout(mul_ln63_2_fu_276_p2)
);

myproject_mul_16s_9ns_25_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
mul_16s_9ns_25_1_0_U4953(
    .din0(data_2_val),
    .din1(mul_ln78_5_fu_292_p1),
    .dout(mul_ln78_5_fu_292_p2)
);

myproject_mul_16s_10ns_26_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_1_0_U4954(
    .din0(mul_ln78_6_fu_308_p0),
    .din1(mul_ln78_6_fu_308_p1),
    .dout(mul_ln78_6_fu_308_p2)
);

myproject_mul_16s_11s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11s_26_1_1_U4955(
    .din0(mul_ln63_3_fu_324_p0),
    .din1(mul_ln63_3_fu_324_p1),
    .dout(mul_ln63_3_fu_324_p2)
);

myproject_mul_16s_9ns_25_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
mul_16s_9ns_25_1_0_U4956(
    .din0(mul_ln78_7_fu_348_p0),
    .din1(mul_ln78_7_fu_348_p1),
    .dout(mul_ln78_7_fu_348_p2)
);

myproject_mul_16s_10s_26_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_1_0_U4957(
    .din0(mul_ln78_8_fu_364_p0),
    .din1(mul_ln78_8_fu_364_p1),
    .dout(mul_ln78_8_fu_364_p2)
);

myproject_mul_16s_11ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11ns_26_1_1_U4958(
    .din0(mul_ln63_4_fu_380_p0),
    .din1(mul_ln63_4_fu_380_p1),
    .dout(mul_ln63_4_fu_380_p2)
);

myproject_mul_16s_9ns_25_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
mul_16s_9ns_25_1_0_U4959(
    .din0(mul_ln78_9_fu_396_p0),
    .din1(mul_ln78_9_fu_396_p1),
    .dout(mul_ln78_9_fu_396_p2)
);

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_0_int_reg <= add_ln76_2_fu_437_p2;
        ap_return_1_int_reg <= add_ln76_5_fu_453_p2;
        ap_return_2_int_reg <= add_ln76_8_fu_467_p2;
        ap_return_3_int_reg <= add_ln76_11_fu_482_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        trunc_ln63_10_reg_567 <= {{mul_ln63_3_fu_324_p2[25:10]}};
        trunc_ln63_11_reg_572 <= {{mul_ln78_7_fu_348_p2[24:10]}};
        trunc_ln63_12_reg_577 <= {{mul_ln78_8_fu_364_p2[25:10]}};
        trunc_ln63_13_reg_582 <= {{mul_ln63_4_fu_380_p2[25:10]}};
        trunc_ln63_14_reg_587 <= {{mul_ln78_9_fu_396_p2[24:10]}};
        trunc_ln63_1_reg_517 <= {{mul_ln78_1_fu_122_p2[24:10]}};
        trunc_ln63_2_reg_522 <= {{mul_ln78_2_fu_138_p2[25:10]}};
        trunc_ln63_3_reg_527 <= {{mul_ln78_3_fu_154_p2[25:10]}};
        trunc_ln63_4_reg_532 <= {{sub_ln78_1_fu_204_p2[23:10]}};
        trunc_ln63_5_reg_537 <= {{mul_ln78_4_fu_220_p2[25:10]}};
        trunc_ln63_6_reg_542 <= {{mul_ln63_fu_236_p2[25:10]}};
        trunc_ln63_7_reg_547 <= {{mul_ln63_1_fu_252_p2[25:10]}};
        trunc_ln63_8_reg_552 <= {{mul_ln63_2_fu_276_p2[25:10]}};
        trunc_ln63_9_reg_557 <= {{mul_ln78_5_fu_292_p2[24:10]}};
        trunc_ln63_s_reg_562 <= {{mul_ln78_6_fu_308_p2[25:10]}};
        trunc_ln_reg_512 <= {{mul_ln78_fu_106_p2[25:10]}};
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_0 = ap_return_0_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_0 = add_ln76_2_fu_437_p2;
    end else begin
        ap_return_0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_1 = ap_return_1_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_1 = add_ln76_5_fu_453_p2;
    end else begin
        ap_return_1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_2 = ap_return_2_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_2 = add_ln76_8_fu_467_p2;
    end else begin
        ap_return_2 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_3 = ap_return_3_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_3 = add_ln76_11_fu_482_p2;
    end else begin
        ap_return_3 = 'bx;
    end
end

assign add_ln76_10_fu_477_p2 = ($signed(trunc_ln63_10_reg_567) + $signed(sext_ln63_5_fu_424_p1));

assign add_ln76_11_fu_482_p2 = (add_ln76_10_fu_477_p2 + add_ln76_9_fu_473_p2);

assign add_ln76_1_fu_431_p2 = ($signed(sext_ln63_4_fu_421_p1) + $signed(sext_ln63_1_fu_415_p1));

assign add_ln76_2_fu_437_p2 = (add_ln76_1_fu_431_p2 + add_ln76_fu_427_p2);

assign add_ln76_3_fu_443_p2 = (trunc_ln63_5_reg_537 + trunc_ln63_12_reg_577);

assign add_ln76_4_fu_447_p2 = ($signed(sext_ln63_fu_412_p1) + $signed(sext_ln63_2_fu_418_p1));

assign add_ln76_5_fu_453_p2 = (add_ln76_4_fu_447_p2 + add_ln76_3_fu_443_p2);

assign add_ln76_6_fu_459_p2 = (trunc_ln63_6_reg_542 + trunc_ln63_2_reg_522);

assign add_ln76_7_fu_463_p2 = (trunc_ln63_s_reg_562 + trunc_ln63_13_reg_582);

assign add_ln76_8_fu_467_p2 = (add_ln76_7_fu_463_p2 + add_ln76_6_fu_459_p2);

assign add_ln76_9_fu_473_p2 = (trunc_ln63_7_reg_547 + trunc_ln63_3_reg_527);

assign add_ln76_fu_427_p2 = (trunc_ln63_8_reg_552 + trunc_ln_reg_512);

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign mul_ln63_1_fu_252_p0 = sext_ln74_2_fu_170_p1;

assign mul_ln63_1_fu_252_p1 = 26'd67108303;

assign mul_ln63_2_fu_276_p0 = sext_ln74_3_fu_268_p1;

assign mul_ln63_2_fu_276_p1 = 26'd67108314;

assign mul_ln63_3_fu_324_p0 = sext_ln74_3_fu_268_p1;

assign mul_ln63_3_fu_324_p1 = 26'd67108251;

assign mul_ln63_4_fu_380_p0 = sext_ln63_3_fu_340_p1;

assign mul_ln63_4_fu_380_p1 = 26'd539;

assign mul_ln63_fu_236_p0 = sext_ln74_2_fu_170_p1;

assign mul_ln63_fu_236_p1 = 26'd67108210;

assign mul_ln78_1_fu_122_p1 = 25'd211;

assign mul_ln78_2_fu_138_p0 = sext_ln74_1_fu_102_p1;

assign mul_ln78_2_fu_138_p1 = 26'd457;

assign mul_ln78_3_fu_154_p0 = sext_ln74_1_fu_102_p1;

assign mul_ln78_3_fu_154_p1 = 26'd67108415;

assign mul_ln78_4_fu_220_p0 = sext_ln74_2_fu_170_p1;

assign mul_ln78_4_fu_220_p1 = 26'd340;

assign mul_ln78_5_fu_292_p1 = 25'd158;

assign mul_ln78_6_fu_308_p0 = sext_ln74_3_fu_268_p1;

assign mul_ln78_6_fu_308_p1 = 26'd363;

assign mul_ln78_7_fu_348_p0 = sext_ln74_5_fu_344_p1;

assign mul_ln78_7_fu_348_p1 = 25'd139;

assign mul_ln78_8_fu_364_p0 = sext_ln63_3_fu_340_p1;

assign mul_ln78_8_fu_364_p1 = 26'd67108407;

assign mul_ln78_9_fu_396_p0 = sext_ln74_5_fu_344_p1;

assign mul_ln78_9_fu_396_p1 = 25'd213;

assign mul_ln78_fu_106_p0 = sext_ln74_1_fu_102_p1;

assign mul_ln78_fu_106_p1 = 26'd67108419;

assign sext_ln63_1_fu_415_p1 = $signed(trunc_ln63_4_reg_532);

assign sext_ln63_2_fu_418_p1 = $signed(trunc_ln63_9_reg_557);

assign sext_ln63_3_fu_340_p0 = data_3_val;

assign sext_ln63_3_fu_340_p1 = sext_ln63_3_fu_340_p0;

assign sext_ln63_4_fu_421_p1 = $signed(trunc_ln63_11_reg_572);

assign sext_ln63_5_fu_424_p1 = $signed(trunc_ln63_14_reg_587);

assign sext_ln63_fu_412_p1 = $signed(trunc_ln63_1_reg_517);

assign sext_ln74_1_fu_102_p0 = data_0_val;

assign sext_ln74_1_fu_102_p1 = sext_ln74_1_fu_102_p0;

assign sext_ln74_2_fu_170_p0 = data_1_val;

assign sext_ln74_2_fu_170_p1 = sext_ln74_2_fu_170_p0;

assign sext_ln74_3_fu_268_p0 = data_2_val;

assign sext_ln74_3_fu_268_p1 = sext_ln74_3_fu_268_p0;

assign sext_ln74_5_fu_344_p0 = data_3_val;

assign sext_ln74_5_fu_344_p1 = sext_ln74_5_fu_344_p0;

assign sext_ln78_598_fu_200_p1 = $signed(shl_ln78_1_fu_192_p3);

assign sext_ln78_fu_182_p1 = $signed(shl_ln_fu_174_p3);

assign shl_ln78_1_fu_192_p1 = data_1_val;

assign shl_ln78_1_fu_192_p3 = {{shl_ln78_1_fu_192_p1}, {1'd0}};

assign shl_ln_fu_174_p1 = data_1_val;

assign shl_ln_fu_174_p3 = {{shl_ln_fu_174_p1}, {7'd0}};

assign sub_ln78_1_fu_204_p2 = ($signed(sub_ln78_fu_186_p2) - $signed(sext_ln78_598_fu_200_p1));

assign sub_ln78_fu_186_p2 = ($signed(24'd0) - $signed(sext_ln78_fu_182_p1));

endmodule //myproject_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config3_2_s
