// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<4> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::ap_ST_fsm_pp0_stage0 = "1";
const sc_lv<4> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::ap_ST_fsm_pp0_stage1 = "10";
const sc_lv<4> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::ap_ST_fsm_pp0_stage2 = "100";
const sc_lv<4> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::ap_ST_fsm_pp0_stage3 = "1000";
const bool dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::ap_const_boolean_1 = true;
const sc_lv<32> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::ap_const_boolean_0 = false;
const sc_lv<32> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::ap_const_lv32_3 = "11";
const sc_lv<32> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::ap_const_lv32_1 = "1";
const sc_lv<32> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::ap_const_lv32_2 = "10";
const sc_lv<4> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::ap_const_lv4_1 = "1";
const sc_lv<32> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::ap_const_lv32_A = "1010";
const sc_lv<32> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::ap_const_lv32_19 = "11001";
const sc_lv<4> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::ap_const_lv4_2 = "10";
const sc_lv<4> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::ap_const_lv4_3 = "11";
const sc_lv<4> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::ap_const_lv4_4 = "100";
const sc_lv<4> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::ap_const_lv4_5 = "101";
const sc_lv<4> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::ap_const_lv4_6 = "110";
const sc_lv<4> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::ap_const_lv4_7 = "111";
const sc_lv<16> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::ap_const_lv16_0 = "0000000000000000";
const sc_lv<2> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::ap_const_lv2_1 = "1";
const sc_lv<10> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::ap_const_lv10_0 = "0000000000";

dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s(sc_module_name name) : sc_module(name), mVcdFile(0) {
    myproject_mux_42_16_1_1_U31 = new myproject_mux_42_16_1_1<1,1,16,16,16,16,2,16>("myproject_mux_42_16_1_1_U31");
    myproject_mux_42_16_1_1_U31->din0(ap_var_for_const0);
    myproject_mux_42_16_1_1_U31->din1(ap_var_for_const0);
    myproject_mux_42_16_1_1_U31->din2(ap_var_for_const0);
    myproject_mux_42_16_1_1_U31->din3(ap_var_for_const0);
    myproject_mux_42_16_1_1_U31->din4(trunc_ln15_reg_742);
    myproject_mux_42_16_1_1_U31->dout(tmp_42_fu_581_p6);
    myproject_mux_42_16_1_1_U32 = new myproject_mux_42_16_1_1<1,1,16,16,16,16,2,16>("myproject_mux_42_16_1_1_U32");
    myproject_mux_42_16_1_1_U32->din0(ap_var_for_const0);
    myproject_mux_42_16_1_1_U32->din1(ap_var_for_const0);
    myproject_mux_42_16_1_1_U32->din2(ap_var_for_const0);
    myproject_mux_42_16_1_1_U32->din3(ap_var_for_const0);
    myproject_mux_42_16_1_1_U32->din4(tmp_43_fu_599_p5);
    myproject_mux_42_16_1_1_U32->dout(tmp_43_fu_599_p6);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_acc_1_V_fu_649_p2);
    sensitive << ( add_ln703_1524_fu_644_p2 );
    sensitive << ( add_ln703_1522_fu_634_p2 );

    SC_METHOD(thread_add_ln42_1_fu_410_p2);
    sensitive << ( trunc_ln42_reg_682 );

    SC_METHOD(thread_add_ln42_2_fu_420_p2);
    sensitive << ( trunc_ln42_reg_682 );

    SC_METHOD(thread_add_ln42_3_fu_466_p2);
    sensitive << ( trunc_ln42_reg_682 );

    SC_METHOD(thread_add_ln42_4_fu_476_p2);
    sensitive << ( trunc_ln42_reg_682 );

    SC_METHOD(thread_add_ln42_5_fu_526_p2);
    sensitive << ( trunc_ln42_reg_682 );

    SC_METHOD(thread_add_ln42_6_fu_536_p2);
    sensitive << ( trunc_ln42_reg_682 );

    SC_METHOD(thread_add_ln42_fu_363_p2);
    sensitive << ( trunc_ln42_fu_359_p1 );

    SC_METHOD(thread_add_ln703_1519_fu_618_p2);
    sensitive << ( trunc_ln708_3197_reg_748 );
    sensitive << ( trunc_ln708_3199_fu_556_p4 );

    SC_METHOD(thread_add_ln703_1520_fu_623_p2);
    sensitive << ( trunc_ln708_3195_reg_717 );
    sensitive << ( add_ln703_1519_fu_618_p2 );

    SC_METHOD(thread_add_ln703_1522_fu_634_p2);
    sensitive << ( trunc_ln708_s_reg_702 );
    sensitive << ( tmp_43_fu_599_p6 );

    SC_METHOD(thread_add_ln703_1523_fu_639_p2);
    sensitive << ( trunc_ln708_3198_reg_753 );
    sensitive << ( trunc_ln708_3200_fu_571_p4 );

    SC_METHOD(thread_add_ln703_1524_fu_644_p2);
    sensitive << ( trunc_ln708_3196_reg_722 );
    sensitive << ( add_ln703_1523_fu_639_p2 );

    SC_METHOD(thread_add_ln703_fu_613_p2);
    sensitive << ( trunc_ln4_reg_697 );
    sensitive << ( tmp_42_fu_581_p6 );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);
    sensitive << ( ap_start );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);
    sensitive << ( ap_start );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_ce );

    SC_METHOD(thread_ap_block_pp0_stage1);

    SC_METHOD(thread_ap_block_pp0_stage1_11001);

    SC_METHOD(thread_ap_block_pp0_stage1_subdone);
    sensitive << ( ap_ce );

    SC_METHOD(thread_ap_block_pp0_stage2);

    SC_METHOD(thread_ap_block_pp0_stage2_11001);

    SC_METHOD(thread_ap_block_pp0_stage2_subdone);
    sensitive << ( ap_ce );

    SC_METHOD(thread_ap_block_pp0_stage3);

    SC_METHOD(thread_ap_block_pp0_stage3_11001);

    SC_METHOD(thread_ap_block_pp0_stage3_subdone);
    sensitive << ( ap_ce );

    SC_METHOD(thread_ap_block_state1_pp0_stage0_iter0);
    sensitive << ( ap_start );

    SC_METHOD(thread_ap_block_state2_pp0_stage1_iter0);

    SC_METHOD(thread_ap_block_state3_pp0_stage2_iter0);

    SC_METHOD(thread_ap_block_state4_pp0_stage3_iter0);

    SC_METHOD(thread_ap_block_state5_pp0_stage0_iter1);

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_ce );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_enable_reg_pp0_iter0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0_reg );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_ap_idle_pp0_0to0);
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_ap_idle_pp0_1to1);
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( ap_block_pp0_stage3_11001 );
    sensitive << ( ap_ce );

    SC_METHOD(thread_ap_reset_idle_pp0);
    sensitive << ( ap_start );
    sensitive << ( ap_idle_pp0_0to0 );

    SC_METHOD(thread_ap_return);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_ce );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( acc_1_V_fu_649_p2 );
    sensitive << ( sext_ln728_fu_663_p1 );

    SC_METHOD(thread_mul_ln1118_4016_fu_180_p0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage1 );
    sensitive << ( sext_ln1116_cast_fu_374_p1 );

    SC_METHOD(thread_mul_ln1118_4016_fu_180_p1);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( weights_V_q1 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage1 );

    SC_METHOD(thread_mul_ln1118_4016_fu_180_p2);
    sensitive << ( mul_ln1118_4016_fu_180_p0 );
    sensitive << ( mul_ln1118_4016_fu_180_p1 );

    SC_METHOD(thread_mul_ln1118_4017_fu_177_p0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage2 );
    sensitive << ( sext_ln1116_1720_cast_fu_430_p1 );

    SC_METHOD(thread_mul_ln1118_4017_fu_177_p1);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( weights_V_q0 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage2 );

    SC_METHOD(thread_mul_ln1118_4017_fu_177_p2);
    sensitive << ( mul_ln1118_4017_fu_177_p0 );
    sensitive << ( mul_ln1118_4017_fu_177_p1 );

    SC_METHOD(thread_mul_ln1118_4018_fu_182_p0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage2 );
    sensitive << ( sext_ln1116_1720_cast_fu_430_p1 );

    SC_METHOD(thread_mul_ln1118_4018_fu_182_p1);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( weights_V_q1 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage2 );

    SC_METHOD(thread_mul_ln1118_4018_fu_182_p2);
    sensitive << ( mul_ln1118_4018_fu_182_p0 );
    sensitive << ( mul_ln1118_4018_fu_182_p1 );

    SC_METHOD(thread_mul_ln1118_4019_fu_178_p0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( ap_block_pp0_stage3 );
    sensitive << ( sext_ln1116_1721_cast_fu_490_p1 );

    SC_METHOD(thread_mul_ln1118_4019_fu_178_p1);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( weights_V_q0 );
    sensitive << ( ap_block_pp0_stage3 );

    SC_METHOD(thread_mul_ln1118_4019_fu_178_p2);
    sensitive << ( mul_ln1118_4019_fu_178_p0 );
    sensitive << ( mul_ln1118_4019_fu_178_p1 );

    SC_METHOD(thread_mul_ln1118_4020_fu_179_p0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( ap_block_pp0_stage3 );
    sensitive << ( sext_ln1116_1721_cast_fu_490_p1 );

    SC_METHOD(thread_mul_ln1118_4020_fu_179_p1);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( weights_V_q1 );
    sensitive << ( ap_block_pp0_stage3 );

    SC_METHOD(thread_mul_ln1118_4020_fu_179_p2);
    sensitive << ( mul_ln1118_4020_fu_179_p0 );
    sensitive << ( mul_ln1118_4020_fu_179_p1 );

    SC_METHOD(thread_mul_ln1118_4021_fu_183_p0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( sext_ln1116_1722_cast_fu_546_p1 );

    SC_METHOD(thread_mul_ln1118_4021_fu_183_p1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( weights_V_q0 );

    SC_METHOD(thread_mul_ln1118_4021_fu_183_p2);
    sensitive << ( mul_ln1118_4021_fu_183_p0 );
    sensitive << ( mul_ln1118_4021_fu_183_p1 );

    SC_METHOD(thread_mul_ln1118_4022_fu_184_p0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( sext_ln1116_1722_cast_fu_546_p1 );

    SC_METHOD(thread_mul_ln1118_4022_fu_184_p1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( weights_V_q1 );

    SC_METHOD(thread_mul_ln1118_4022_fu_184_p2);
    sensitive << ( mul_ln1118_4022_fu_184_p0 );
    sensitive << ( mul_ln1118_4022_fu_184_p1 );

    SC_METHOD(thread_mul_ln1118_fu_181_p0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage1 );
    sensitive << ( sext_ln1116_cast_fu_374_p1 );

    SC_METHOD(thread_mul_ln1118_fu_181_p1);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( weights_V_q0 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage1 );

    SC_METHOD(thread_mul_ln1118_fu_181_p2);
    sensitive << ( mul_ln1118_fu_181_p0 );
    sensitive << ( mul_ln1118_fu_181_p1 );

    SC_METHOD(thread_p_Val2_s_fu_628_p2);
    sensitive << ( add_ln703_1520_fu_623_p2 );
    sensitive << ( add_ln703_fu_613_p2 );

    SC_METHOD(thread_sext_ln1116_1720_cast_fu_430_p1);
    sensitive << ( ap_port_reg_data_1_V_read );

    SC_METHOD(thread_sext_ln1116_1721_cast_fu_490_p1);
    sensitive << ( ap_port_reg_data_2_V_read );

    SC_METHOD(thread_sext_ln1116_1722_cast_fu_546_p1);
    sensitive << ( data_3_V_read_2_reg_737 );

    SC_METHOD(thread_sext_ln1116_cast_fu_374_p1);
    sensitive << ( ap_port_reg_data_0_V_read );

    SC_METHOD(thread_sext_ln728_fu_663_p1);
    sensitive << ( shl_ln_fu_655_p3 );

    SC_METHOD(thread_shl_ln_fu_655_p3);
    sensitive << ( p_Val2_s_fu_628_p2 );

    SC_METHOD(thread_tmp_43_fu_599_p5);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( trunc_ln15_reg_742 );

    SC_METHOD(thread_trunc_ln15_fu_486_p1);
    sensitive << ( ap_port_reg_biases_V_offset );

    SC_METHOD(thread_trunc_ln42_fu_359_p1);
    sensitive << ( weights_V_offset );

    SC_METHOD(thread_trunc_ln708_3199_fu_556_p4);
    sensitive << ( mul_ln1118_4021_fu_183_p2 );

    SC_METHOD(thread_trunc_ln708_3200_fu_571_p4);
    sensitive << ( mul_ln1118_4022_fu_184_p2 );

    SC_METHOD(thread_weights_V_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( zext_ln15_fu_354_p1 );
    sensitive << ( zext_ln42_1_fu_415_p1 );
    sensitive << ( ap_block_pp0_stage1 );
    sensitive << ( zext_ln42_3_fu_471_p1 );
    sensitive << ( ap_block_pp0_stage2 );
    sensitive << ( zext_ln42_5_fu_531_p1 );
    sensitive << ( ap_block_pp0_stage3 );

    SC_METHOD(thread_weights_V_address1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( zext_ln42_fu_369_p1 );
    sensitive << ( ap_block_pp0_stage1 );
    sensitive << ( zext_ln42_2_fu_425_p1 );
    sensitive << ( ap_block_pp0_stage2 );
    sensitive << ( zext_ln42_4_fu_481_p1 );
    sensitive << ( ap_block_pp0_stage3 );
    sensitive << ( zext_ln42_6_fu_541_p1 );

    SC_METHOD(thread_weights_V_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( ap_block_pp0_stage3_11001 );
    sensitive << ( ap_ce );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage1_11001 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage2_11001 );

    SC_METHOD(thread_weights_V_ce1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( ap_block_pp0_stage3_11001 );
    sensitive << ( ap_ce );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage1_11001 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage2_11001 );

    SC_METHOD(thread_zext_ln15_fu_354_p1);
    sensitive << ( weights_V_offset );

    SC_METHOD(thread_zext_ln42_1_fu_415_p1);
    sensitive << ( add_ln42_1_fu_410_p2 );

    SC_METHOD(thread_zext_ln42_2_fu_425_p1);
    sensitive << ( add_ln42_2_fu_420_p2 );

    SC_METHOD(thread_zext_ln42_3_fu_471_p1);
    sensitive << ( add_ln42_3_fu_466_p2 );

    SC_METHOD(thread_zext_ln42_4_fu_481_p1);
    sensitive << ( add_ln42_4_fu_476_p2 );

    SC_METHOD(thread_zext_ln42_5_fu_531_p1);
    sensitive << ( add_ln42_5_fu_526_p2 );

    SC_METHOD(thread_zext_ln42_6_fu_541_p1);
    sensitive << ( add_ln42_6_fu_536_p2 );

    SC_METHOD(thread_zext_ln42_fu_369_p1);
    sensitive << ( add_ln42_fu_363_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_block_pp0_stage3_subdone );
    sensitive << ( ap_reset_idle_pp0 );
    sensitive << ( ap_idle_pp0_1to1 );
    sensitive << ( ap_block_pp0_stage1_subdone );
    sensitive << ( ap_block_pp0_stage2_subdone );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "0001";
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter0_reg = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, ap_ce, "(port)ap_ce");
    sc_trace(mVcdFile, data_0_V_read, "(port)data_0_V_read");
    sc_trace(mVcdFile, data_1_V_read, "(port)data_1_V_read");
    sc_trace(mVcdFile, data_2_V_read, "(port)data_2_V_read");
    sc_trace(mVcdFile, data_3_V_read, "(port)data_3_V_read");
    sc_trace(mVcdFile, weights_V_address0, "(port)weights_V_address0");
    sc_trace(mVcdFile, weights_V_ce0, "(port)weights_V_ce0");
    sc_trace(mVcdFile, weights_V_q0, "(port)weights_V_q0");
    sc_trace(mVcdFile, weights_V_address1, "(port)weights_V_address1");
    sc_trace(mVcdFile, weights_V_ce1, "(port)weights_V_ce1");
    sc_trace(mVcdFile, weights_V_q1, "(port)weights_V_q1");
    sc_trace(mVcdFile, weights_V_offset, "(port)weights_V_offset");
    sc_trace(mVcdFile, biases_V_offset, "(port)biases_V_offset");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage3, "ap_CS_fsm_pp0_stage3");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage3_iter0, "ap_block_state4_pp0_stage3_iter0");
    sc_trace(mVcdFile, ap_block_pp0_stage3_11001, "ap_block_pp0_stage3_11001");
    sc_trace(mVcdFile, ap_block_state1_pp0_stage0_iter0, "ap_block_state1_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage0_iter1, "ap_block_state5_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, trunc_ln42_fu_359_p1, "trunc_ln42_fu_359_p1");
    sc_trace(mVcdFile, trunc_ln42_reg_682, "trunc_ln42_reg_682");
    sc_trace(mVcdFile, trunc_ln4_reg_697, "trunc_ln4_reg_697");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage1, "ap_CS_fsm_pp0_stage1");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage1_iter0, "ap_block_state2_pp0_stage1_iter0");
    sc_trace(mVcdFile, ap_block_pp0_stage1_11001, "ap_block_pp0_stage1_11001");
    sc_trace(mVcdFile, trunc_ln708_s_reg_702, "trunc_ln708_s_reg_702");
    sc_trace(mVcdFile, trunc_ln708_3195_reg_717, "trunc_ln708_3195_reg_717");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage2, "ap_CS_fsm_pp0_stage2");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage2_iter0, "ap_block_state3_pp0_stage2_iter0");
    sc_trace(mVcdFile, ap_block_pp0_stage2_11001, "ap_block_pp0_stage2_11001");
    sc_trace(mVcdFile, trunc_ln708_3196_reg_722, "trunc_ln708_3196_reg_722");
    sc_trace(mVcdFile, data_3_V_read_2_reg_737, "data_3_V_read_2_reg_737");
    sc_trace(mVcdFile, trunc_ln15_fu_486_p1, "trunc_ln15_fu_486_p1");
    sc_trace(mVcdFile, trunc_ln15_reg_742, "trunc_ln15_reg_742");
    sc_trace(mVcdFile, trunc_ln708_3197_reg_748, "trunc_ln708_3197_reg_748");
    sc_trace(mVcdFile, trunc_ln708_3198_reg_753, "trunc_ln708_3198_reg_753");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0_reg, "ap_enable_reg_pp0_iter0_reg");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_block_pp0_stage3_subdone, "ap_block_pp0_stage3_subdone");
    sc_trace(mVcdFile, ap_port_reg_data_0_V_read, "ap_port_reg_data_0_V_read");
    sc_trace(mVcdFile, ap_port_reg_data_1_V_read, "ap_port_reg_data_1_V_read");
    sc_trace(mVcdFile, ap_port_reg_data_2_V_read, "ap_port_reg_data_2_V_read");
    sc_trace(mVcdFile, ap_port_reg_data_3_V_read, "ap_port_reg_data_3_V_read");
    sc_trace(mVcdFile, ap_port_reg_biases_V_offset, "ap_port_reg_biases_V_offset");
    sc_trace(mVcdFile, zext_ln15_fu_354_p1, "zext_ln15_fu_354_p1");
    sc_trace(mVcdFile, zext_ln42_fu_369_p1, "zext_ln42_fu_369_p1");
    sc_trace(mVcdFile, zext_ln42_1_fu_415_p1, "zext_ln42_1_fu_415_p1");
    sc_trace(mVcdFile, ap_block_pp0_stage1, "ap_block_pp0_stage1");
    sc_trace(mVcdFile, zext_ln42_2_fu_425_p1, "zext_ln42_2_fu_425_p1");
    sc_trace(mVcdFile, zext_ln42_3_fu_471_p1, "zext_ln42_3_fu_471_p1");
    sc_trace(mVcdFile, ap_block_pp0_stage2, "ap_block_pp0_stage2");
    sc_trace(mVcdFile, zext_ln42_4_fu_481_p1, "zext_ln42_4_fu_481_p1");
    sc_trace(mVcdFile, zext_ln42_5_fu_531_p1, "zext_ln42_5_fu_531_p1");
    sc_trace(mVcdFile, ap_block_pp0_stage3, "ap_block_pp0_stage3");
    sc_trace(mVcdFile, zext_ln42_6_fu_541_p1, "zext_ln42_6_fu_541_p1");
    sc_trace(mVcdFile, mul_ln1118_4017_fu_177_p0, "mul_ln1118_4017_fu_177_p0");
    sc_trace(mVcdFile, sext_ln1116_1720_cast_fu_430_p1, "sext_ln1116_1720_cast_fu_430_p1");
    sc_trace(mVcdFile, mul_ln1118_4017_fu_177_p1, "mul_ln1118_4017_fu_177_p1");
    sc_trace(mVcdFile, mul_ln1118_4019_fu_178_p0, "mul_ln1118_4019_fu_178_p0");
    sc_trace(mVcdFile, sext_ln1116_1721_cast_fu_490_p1, "sext_ln1116_1721_cast_fu_490_p1");
    sc_trace(mVcdFile, mul_ln1118_4019_fu_178_p1, "mul_ln1118_4019_fu_178_p1");
    sc_trace(mVcdFile, mul_ln1118_4020_fu_179_p0, "mul_ln1118_4020_fu_179_p0");
    sc_trace(mVcdFile, mul_ln1118_4020_fu_179_p1, "mul_ln1118_4020_fu_179_p1");
    sc_trace(mVcdFile, mul_ln1118_4016_fu_180_p0, "mul_ln1118_4016_fu_180_p0");
    sc_trace(mVcdFile, sext_ln1116_cast_fu_374_p1, "sext_ln1116_cast_fu_374_p1");
    sc_trace(mVcdFile, mul_ln1118_4016_fu_180_p1, "mul_ln1118_4016_fu_180_p1");
    sc_trace(mVcdFile, mul_ln1118_fu_181_p0, "mul_ln1118_fu_181_p0");
    sc_trace(mVcdFile, mul_ln1118_fu_181_p1, "mul_ln1118_fu_181_p1");
    sc_trace(mVcdFile, mul_ln1118_4018_fu_182_p0, "mul_ln1118_4018_fu_182_p0");
    sc_trace(mVcdFile, mul_ln1118_4018_fu_182_p1, "mul_ln1118_4018_fu_182_p1");
    sc_trace(mVcdFile, mul_ln1118_4021_fu_183_p0, "mul_ln1118_4021_fu_183_p0");
    sc_trace(mVcdFile, sext_ln1116_1722_cast_fu_546_p1, "sext_ln1116_1722_cast_fu_546_p1");
    sc_trace(mVcdFile, mul_ln1118_4021_fu_183_p1, "mul_ln1118_4021_fu_183_p1");
    sc_trace(mVcdFile, mul_ln1118_4022_fu_184_p0, "mul_ln1118_4022_fu_184_p0");
    sc_trace(mVcdFile, mul_ln1118_4022_fu_184_p1, "mul_ln1118_4022_fu_184_p1");
    sc_trace(mVcdFile, add_ln42_fu_363_p2, "add_ln42_fu_363_p2");
    sc_trace(mVcdFile, mul_ln1118_fu_181_p2, "mul_ln1118_fu_181_p2");
    sc_trace(mVcdFile, mul_ln1118_4016_fu_180_p2, "mul_ln1118_4016_fu_180_p2");
    sc_trace(mVcdFile, add_ln42_1_fu_410_p2, "add_ln42_1_fu_410_p2");
    sc_trace(mVcdFile, add_ln42_2_fu_420_p2, "add_ln42_2_fu_420_p2");
    sc_trace(mVcdFile, mul_ln1118_4017_fu_177_p2, "mul_ln1118_4017_fu_177_p2");
    sc_trace(mVcdFile, mul_ln1118_4018_fu_182_p2, "mul_ln1118_4018_fu_182_p2");
    sc_trace(mVcdFile, add_ln42_3_fu_466_p2, "add_ln42_3_fu_466_p2");
    sc_trace(mVcdFile, add_ln42_4_fu_476_p2, "add_ln42_4_fu_476_p2");
    sc_trace(mVcdFile, mul_ln1118_4019_fu_178_p2, "mul_ln1118_4019_fu_178_p2");
    sc_trace(mVcdFile, mul_ln1118_4020_fu_179_p2, "mul_ln1118_4020_fu_179_p2");
    sc_trace(mVcdFile, add_ln42_5_fu_526_p2, "add_ln42_5_fu_526_p2");
    sc_trace(mVcdFile, add_ln42_6_fu_536_p2, "add_ln42_6_fu_536_p2");
    sc_trace(mVcdFile, mul_ln1118_4021_fu_183_p2, "mul_ln1118_4021_fu_183_p2");
    sc_trace(mVcdFile, mul_ln1118_4022_fu_184_p2, "mul_ln1118_4022_fu_184_p2");
    sc_trace(mVcdFile, tmp_43_fu_599_p5, "tmp_43_fu_599_p5");
    sc_trace(mVcdFile, tmp_42_fu_581_p6, "tmp_42_fu_581_p6");
    sc_trace(mVcdFile, trunc_ln708_3199_fu_556_p4, "trunc_ln708_3199_fu_556_p4");
    sc_trace(mVcdFile, add_ln703_1519_fu_618_p2, "add_ln703_1519_fu_618_p2");
    sc_trace(mVcdFile, add_ln703_1520_fu_623_p2, "add_ln703_1520_fu_623_p2");
    sc_trace(mVcdFile, add_ln703_fu_613_p2, "add_ln703_fu_613_p2");
    sc_trace(mVcdFile, tmp_43_fu_599_p6, "tmp_43_fu_599_p6");
    sc_trace(mVcdFile, trunc_ln708_3200_fu_571_p4, "trunc_ln708_3200_fu_571_p4");
    sc_trace(mVcdFile, add_ln703_1523_fu_639_p2, "add_ln703_1523_fu_639_p2");
    sc_trace(mVcdFile, add_ln703_1524_fu_644_p2, "add_ln703_1524_fu_644_p2");
    sc_trace(mVcdFile, add_ln703_1522_fu_634_p2, "add_ln703_1522_fu_634_p2");
    sc_trace(mVcdFile, p_Val2_s_fu_628_p2, "p_Val2_s_fu_628_p2");
    sc_trace(mVcdFile, shl_ln_fu_655_p3, "shl_ln_fu_655_p3");
    sc_trace(mVcdFile, acc_1_V_fu_649_p2, "acc_1_V_fu_649_p2");
    sc_trace(mVcdFile, sext_ln728_fu_663_p1, "sext_ln728_fu_663_p1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0_0to0, "ap_idle_pp0_0to0");
    sc_trace(mVcdFile, ap_reset_idle_pp0, "ap_reset_idle_pp0");
    sc_trace(mVcdFile, ap_idle_pp0_1to1, "ap_idle_pp0_1to1");
    sc_trace(mVcdFile, ap_block_pp0_stage1_subdone, "ap_block_pp0_stage1_subdone");
    sc_trace(mVcdFile, ap_block_pp0_stage2_subdone, "ap_block_pp0_stage2_subdone");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
#endif

    }
}

dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::~dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete myproject_mux_42_16_1_1_U31;
    delete myproject_mux_42_16_1_1_U32;
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_lv16_0;
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_pp0_stage0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read())) {
            ap_enable_reg_pp0_iter0_reg = ap_start.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage3_subdone.read(), ap_const_boolean_0))) {
            ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
                    esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_0))) {
            ap_enable_reg_pp0_iter1 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        ap_port_reg_biases_V_offset = biases_V_offset.read();
        ap_port_reg_data_0_V_read = data_0_V_read.read();
        ap_port_reg_data_1_V_read = data_1_V_read.read();
        ap_port_reg_data_2_V_read = data_2_V_read.read();
        ap_port_reg_data_3_V_read = data_3_V_read.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage3_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1))) {
        data_3_V_read_2_reg_737 = ap_port_reg_data_3_V_read.read();
        trunc_ln15_reg_742 = trunc_ln15_fu_486_p1.read();
        trunc_ln708_3197_reg_748 = mul_ln1118_4019_fu_178_p2.read().range(25, 10);
        trunc_ln708_3198_reg_753 = mul_ln1118_4020_fu_179_p2.read().range(25, 10);
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        trunc_ln42_reg_682 = trunc_ln42_fu_359_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0))) {
        trunc_ln4_reg_697 = mul_ln1118_fu_181_p2.read().range(25, 10);
        trunc_ln708_s_reg_702 = mul_ln1118_4016_fu_180_p2.read().range(25, 10);
    }
    if ((esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage2_11001.read(), ap_const_boolean_0))) {
        trunc_ln708_3195_reg_717 = mul_ln1118_4017_fu_177_p2.read().range(25, 10);
        trunc_ln708_3196_reg_722 = mul_ln1118_4018_fu_182_p2.read().range(25, 10);
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_acc_1_V_fu_649_p2() {
    acc_1_V_fu_649_p2 = (!add_ln703_1524_fu_644_p2.read().is_01() || !add_ln703_1522_fu_634_p2.read().is_01())? sc_lv<16>(): (sc_biguint<16>(add_ln703_1524_fu_644_p2.read()) + sc_biguint<16>(add_ln703_1522_fu_634_p2.read()));
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_add_ln42_1_fu_410_p2() {
    add_ln42_1_fu_410_p2 = (!ap_const_lv4_2.is_01() || !trunc_ln42_reg_682.read().is_01())? sc_lv<4>(): (sc_biguint<4>(ap_const_lv4_2) + sc_biguint<4>(trunc_ln42_reg_682.read()));
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_add_ln42_2_fu_420_p2() {
    add_ln42_2_fu_420_p2 = (!ap_const_lv4_3.is_01() || !trunc_ln42_reg_682.read().is_01())? sc_lv<4>(): (sc_biguint<4>(ap_const_lv4_3) + sc_biguint<4>(trunc_ln42_reg_682.read()));
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_add_ln42_3_fu_466_p2() {
    add_ln42_3_fu_466_p2 = (!ap_const_lv4_4.is_01() || !trunc_ln42_reg_682.read().is_01())? sc_lv<4>(): (sc_biguint<4>(ap_const_lv4_4) + sc_biguint<4>(trunc_ln42_reg_682.read()));
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_add_ln42_4_fu_476_p2() {
    add_ln42_4_fu_476_p2 = (!ap_const_lv4_5.is_01() || !trunc_ln42_reg_682.read().is_01())? sc_lv<4>(): (sc_biguint<4>(ap_const_lv4_5) + sc_biguint<4>(trunc_ln42_reg_682.read()));
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_add_ln42_5_fu_526_p2() {
    add_ln42_5_fu_526_p2 = (!ap_const_lv4_6.is_01() || !trunc_ln42_reg_682.read().is_01())? sc_lv<4>(): (sc_biguint<4>(ap_const_lv4_6) + sc_biguint<4>(trunc_ln42_reg_682.read()));
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_add_ln42_6_fu_536_p2() {
    add_ln42_6_fu_536_p2 = (!ap_const_lv4_7.is_01() || !trunc_ln42_reg_682.read().is_01())? sc_lv<4>(): (sc_biguint<4>(ap_const_lv4_7) + sc_biguint<4>(trunc_ln42_reg_682.read()));
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_add_ln42_fu_363_p2() {
    add_ln42_fu_363_p2 = (!ap_const_lv4_1.is_01() || !trunc_ln42_fu_359_p1.read().is_01())? sc_lv<4>(): (sc_biguint<4>(ap_const_lv4_1) + sc_biguint<4>(trunc_ln42_fu_359_p1.read()));
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_add_ln703_1519_fu_618_p2() {
    add_ln703_1519_fu_618_p2 = (!trunc_ln708_3197_reg_748.read().is_01() || !trunc_ln708_3199_fu_556_p4.read().is_01())? sc_lv<16>(): (sc_biguint<16>(trunc_ln708_3197_reg_748.read()) + sc_biguint<16>(trunc_ln708_3199_fu_556_p4.read()));
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_add_ln703_1520_fu_623_p2() {
    add_ln703_1520_fu_623_p2 = (!add_ln703_1519_fu_618_p2.read().is_01() || !trunc_ln708_3195_reg_717.read().is_01())? sc_lv<16>(): (sc_biguint<16>(add_ln703_1519_fu_618_p2.read()) + sc_biguint<16>(trunc_ln708_3195_reg_717.read()));
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_add_ln703_1522_fu_634_p2() {
    add_ln703_1522_fu_634_p2 = (!tmp_43_fu_599_p6.read().is_01() || !trunc_ln708_s_reg_702.read().is_01())? sc_lv<16>(): (sc_biguint<16>(tmp_43_fu_599_p6.read()) + sc_biguint<16>(trunc_ln708_s_reg_702.read()));
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_add_ln703_1523_fu_639_p2() {
    add_ln703_1523_fu_639_p2 = (!trunc_ln708_3198_reg_753.read().is_01() || !trunc_ln708_3200_fu_571_p4.read().is_01())? sc_lv<16>(): (sc_biguint<16>(trunc_ln708_3198_reg_753.read()) + sc_biguint<16>(trunc_ln708_3200_fu_571_p4.read()));
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_add_ln703_1524_fu_644_p2() {
    add_ln703_1524_fu_644_p2 = (!add_ln703_1523_fu_639_p2.read().is_01() || !trunc_ln708_3196_reg_722.read().is_01())? sc_lv<16>(): (sc_biguint<16>(add_ln703_1523_fu_639_p2.read()) + sc_biguint<16>(trunc_ln708_3196_reg_722.read()));
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_add_ln703_fu_613_p2() {
    add_ln703_fu_613_p2 = (!tmp_42_fu_581_p6.read().is_01() || !trunc_ln4_reg_697.read().is_01())? sc_lv<16>(): (sc_biguint<16>(tmp_42_fu_581_p6.read()) + sc_biguint<16>(trunc_ln4_reg_697.read()));
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[0];
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_ap_CS_fsm_pp0_stage1() {
    ap_CS_fsm_pp0_stage1 = ap_CS_fsm.read()[1];
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_ap_CS_fsm_pp0_stage2() {
    ap_CS_fsm_pp0_stage2 = ap_CS_fsm.read()[2];
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_ap_CS_fsm_pp0_stage3() {
    ap_CS_fsm_pp0_stage3 = ap_CS_fsm.read()[3];
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()));
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = (esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_0) || (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())));
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_ap_block_pp0_stage1() {
    ap_block_pp0_stage1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_ap_block_pp0_stage1_11001() {
    ap_block_pp0_stage1_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_ap_block_pp0_stage1_subdone() {
    ap_block_pp0_stage1_subdone = esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_0);
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_ap_block_pp0_stage2() {
    ap_block_pp0_stage2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_ap_block_pp0_stage2_11001() {
    ap_block_pp0_stage2_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_ap_block_pp0_stage2_subdone() {
    ap_block_pp0_stage2_subdone = esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_0);
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_ap_block_pp0_stage3() {
    ap_block_pp0_stage3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_ap_block_pp0_stage3_11001() {
    ap_block_pp0_stage3_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_ap_block_pp0_stage3_subdone() {
    ap_block_pp0_stage3_subdone = esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_0);
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_ap_block_state1_pp0_stage0_iter0() {
    ap_block_state1_pp0_stage0_iter0 = esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_ap_block_state2_pp0_stage1_iter0() {
    ap_block_state2_pp0_stage1_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_ap_block_state3_pp0_stage2_iter0() {
    ap_block_state3_pp0_stage2_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_ap_block_state4_pp0_stage3_iter0() {
    ap_block_state4_pp0_stage3_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_ap_block_state5_pp0_stage0_iter1() {
    ap_block_state5_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_ap_enable_reg_pp0_iter0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read())) {
        ap_enable_reg_pp0_iter0 = ap_start.read();
    } else {
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg.read();
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_idle_pp0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_ap_idle_pp0_0to0() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read())) {
        ap_idle_pp0_0to0 = ap_const_logic_1;
    } else {
        ap_idle_pp0_0to0 = ap_const_logic_0;
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_ap_idle_pp0_1to1() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read())) {
        ap_idle_pp0_1to1 = ap_const_logic_1;
    } else {
        ap_idle_pp0_1to1 = ap_const_logic_0;
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage3_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_ap_reset_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_idle_pp0_0to0.read()))) {
        ap_reset_idle_pp0 = ap_const_logic_1;
    } else {
        ap_reset_idle_pp0 = ap_const_logic_0;
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_ap_return() {
    ap_return = esl_concat<26,33>(esl_concat<16,10>(acc_1_V_fu_649_p2.read(), ap_const_lv10_0), sext_ln728_fu_663_p1.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_mul_ln1118_4016_fu_180_p0() {
    mul_ln1118_4016_fu_180_p0 =  (sc_lv<16>) (sext_ln1116_cast_fu_374_p1.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_mul_ln1118_4016_fu_180_p1() {
    mul_ln1118_4016_fu_180_p1 = weights_V_q1.read();
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_mul_ln1118_4016_fu_180_p2() {
    mul_ln1118_4016_fu_180_p2 = (!mul_ln1118_4016_fu_180_p0.read().is_01() || !mul_ln1118_4016_fu_180_p1.read().is_01())? sc_lv<26>(): sc_bigint<16>(mul_ln1118_4016_fu_180_p0.read()) * sc_bigint<16>(mul_ln1118_4016_fu_180_p1.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_mul_ln1118_4017_fu_177_p0() {
    mul_ln1118_4017_fu_177_p0 =  (sc_lv<16>) (sext_ln1116_1720_cast_fu_430_p1.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_mul_ln1118_4017_fu_177_p1() {
    mul_ln1118_4017_fu_177_p1 = weights_V_q0.read();
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_mul_ln1118_4017_fu_177_p2() {
    mul_ln1118_4017_fu_177_p2 = (!mul_ln1118_4017_fu_177_p0.read().is_01() || !mul_ln1118_4017_fu_177_p1.read().is_01())? sc_lv<26>(): sc_bigint<16>(mul_ln1118_4017_fu_177_p0.read()) * sc_bigint<16>(mul_ln1118_4017_fu_177_p1.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_mul_ln1118_4018_fu_182_p0() {
    mul_ln1118_4018_fu_182_p0 =  (sc_lv<16>) (sext_ln1116_1720_cast_fu_430_p1.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_mul_ln1118_4018_fu_182_p1() {
    mul_ln1118_4018_fu_182_p1 = weights_V_q1.read();
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_mul_ln1118_4018_fu_182_p2() {
    mul_ln1118_4018_fu_182_p2 = (!mul_ln1118_4018_fu_182_p0.read().is_01() || !mul_ln1118_4018_fu_182_p1.read().is_01())? sc_lv<26>(): sc_bigint<16>(mul_ln1118_4018_fu_182_p0.read()) * sc_bigint<16>(mul_ln1118_4018_fu_182_p1.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_mul_ln1118_4019_fu_178_p0() {
    mul_ln1118_4019_fu_178_p0 =  (sc_lv<16>) (sext_ln1116_1721_cast_fu_490_p1.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_mul_ln1118_4019_fu_178_p1() {
    mul_ln1118_4019_fu_178_p1 = weights_V_q0.read();
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_mul_ln1118_4019_fu_178_p2() {
    mul_ln1118_4019_fu_178_p2 = (!mul_ln1118_4019_fu_178_p0.read().is_01() || !mul_ln1118_4019_fu_178_p1.read().is_01())? sc_lv<26>(): sc_bigint<16>(mul_ln1118_4019_fu_178_p0.read()) * sc_bigint<16>(mul_ln1118_4019_fu_178_p1.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_mul_ln1118_4020_fu_179_p0() {
    mul_ln1118_4020_fu_179_p0 =  (sc_lv<16>) (sext_ln1116_1721_cast_fu_490_p1.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_mul_ln1118_4020_fu_179_p1() {
    mul_ln1118_4020_fu_179_p1 = weights_V_q1.read();
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_mul_ln1118_4020_fu_179_p2() {
    mul_ln1118_4020_fu_179_p2 = (!mul_ln1118_4020_fu_179_p0.read().is_01() || !mul_ln1118_4020_fu_179_p1.read().is_01())? sc_lv<26>(): sc_bigint<16>(mul_ln1118_4020_fu_179_p0.read()) * sc_bigint<16>(mul_ln1118_4020_fu_179_p1.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_mul_ln1118_4021_fu_183_p0() {
    mul_ln1118_4021_fu_183_p0 =  (sc_lv<16>) (sext_ln1116_1722_cast_fu_546_p1.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_mul_ln1118_4021_fu_183_p1() {
    mul_ln1118_4021_fu_183_p1 = weights_V_q0.read();
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_mul_ln1118_4021_fu_183_p2() {
    mul_ln1118_4021_fu_183_p2 = (!mul_ln1118_4021_fu_183_p0.read().is_01() || !mul_ln1118_4021_fu_183_p1.read().is_01())? sc_lv<26>(): sc_bigint<16>(mul_ln1118_4021_fu_183_p0.read()) * sc_bigint<16>(mul_ln1118_4021_fu_183_p1.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_mul_ln1118_4022_fu_184_p0() {
    mul_ln1118_4022_fu_184_p0 =  (sc_lv<16>) (sext_ln1116_1722_cast_fu_546_p1.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_mul_ln1118_4022_fu_184_p1() {
    mul_ln1118_4022_fu_184_p1 = weights_V_q1.read();
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_mul_ln1118_4022_fu_184_p2() {
    mul_ln1118_4022_fu_184_p2 = (!mul_ln1118_4022_fu_184_p0.read().is_01() || !mul_ln1118_4022_fu_184_p1.read().is_01())? sc_lv<26>(): sc_bigint<16>(mul_ln1118_4022_fu_184_p0.read()) * sc_bigint<16>(mul_ln1118_4022_fu_184_p1.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_mul_ln1118_fu_181_p0() {
    mul_ln1118_fu_181_p0 =  (sc_lv<16>) (sext_ln1116_cast_fu_374_p1.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_mul_ln1118_fu_181_p1() {
    mul_ln1118_fu_181_p1 = weights_V_q0.read();
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_mul_ln1118_fu_181_p2() {
    mul_ln1118_fu_181_p2 = (!mul_ln1118_fu_181_p0.read().is_01() || !mul_ln1118_fu_181_p1.read().is_01())? sc_lv<26>(): sc_bigint<16>(mul_ln1118_fu_181_p0.read()) * sc_bigint<16>(mul_ln1118_fu_181_p1.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_p_Val2_s_fu_628_p2() {
    p_Val2_s_fu_628_p2 = (!add_ln703_1520_fu_623_p2.read().is_01() || !add_ln703_fu_613_p2.read().is_01())? sc_lv<16>(): (sc_biguint<16>(add_ln703_1520_fu_623_p2.read()) + sc_biguint<16>(add_ln703_fu_613_p2.read()));
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_sext_ln1116_1720_cast_fu_430_p1() {
    sext_ln1116_1720_cast_fu_430_p1 = esl_sext<26,16>(ap_port_reg_data_1_V_read.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_sext_ln1116_1721_cast_fu_490_p1() {
    sext_ln1116_1721_cast_fu_490_p1 = esl_sext<26,16>(ap_port_reg_data_2_V_read.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_sext_ln1116_1722_cast_fu_546_p1() {
    sext_ln1116_1722_cast_fu_546_p1 = esl_sext<26,16>(data_3_V_read_2_reg_737.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_sext_ln1116_cast_fu_374_p1() {
    sext_ln1116_cast_fu_374_p1 = esl_sext<26,16>(ap_port_reg_data_0_V_read.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_sext_ln728_fu_663_p1() {
    sext_ln728_fu_663_p1 = esl_sext<33,26>(shl_ln_fu_655_p3.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_shl_ln_fu_655_p3() {
    shl_ln_fu_655_p3 = esl_concat<16,10>(p_Val2_s_fu_628_p2.read(), ap_const_lv10_0);
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_tmp_43_fu_599_p5() {
    tmp_43_fu_599_p5 = (!ap_const_lv2_1.is_01() || !trunc_ln15_reg_742.read().is_01())? sc_lv<2>(): (sc_biguint<2>(ap_const_lv2_1) + sc_biguint<2>(trunc_ln15_reg_742.read()));
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_trunc_ln15_fu_486_p1() {
    trunc_ln15_fu_486_p1 = ap_port_reg_biases_V_offset.read().range(2-1, 0);
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_trunc_ln42_fu_359_p1() {
    trunc_ln42_fu_359_p1 = weights_V_offset.read().range(4-1, 0);
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_trunc_ln708_3199_fu_556_p4() {
    trunc_ln708_3199_fu_556_p4 = mul_ln1118_4021_fu_183_p2.read().range(25, 10);
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_trunc_ln708_3200_fu_571_p4() {
    trunc_ln708_3200_fu_571_p4 = mul_ln1118_4022_fu_184_p2.read().range(25, 10);
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_weights_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())) {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage3.read(), ap_const_boolean_0))) {
            weights_V_address0 =  (sc_lv<4>) (zext_ln42_5_fu_531_p1.read());
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage2.read(), ap_const_boolean_0))) {
            weights_V_address0 =  (sc_lv<4>) (zext_ln42_3_fu_471_p1.read());
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage1.read(), ap_const_boolean_0))) {
            weights_V_address0 =  (sc_lv<4>) (zext_ln42_1_fu_415_p1.read());
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
            weights_V_address0 =  (sc_lv<4>) (zext_ln15_fu_354_p1.read());
        } else {
            weights_V_address0 = "XXXX";
        }
    } else {
        weights_V_address0 = "XXXX";
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_weights_V_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())) {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage3.read(), ap_const_boolean_0))) {
            weights_V_address1 =  (sc_lv<4>) (zext_ln42_6_fu_541_p1.read());
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage2.read(), ap_const_boolean_0))) {
            weights_V_address1 =  (sc_lv<4>) (zext_ln42_4_fu_481_p1.read());
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage1.read(), ap_const_boolean_0))) {
            weights_V_address1 =  (sc_lv<4>) (zext_ln42_2_fu_425_p1.read());
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
            weights_V_address1 =  (sc_lv<4>) (zext_ln42_fu_369_p1.read());
        } else {
            weights_V_address1 = "XXXX";
        }
    } else {
        weights_V_address1 = "XXXX";
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_weights_V_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage3_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage2_11001.read(), ap_const_boolean_0)))) {
        weights_V_ce0 = ap_const_logic_1;
    } else {
        weights_V_ce0 = ap_const_logic_0;
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_weights_V_ce1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage3_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage2_11001.read(), ap_const_boolean_0)))) {
        weights_V_ce1 = ap_const_logic_1;
    } else {
        weights_V_ce1 = ap_const_logic_0;
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_zext_ln15_fu_354_p1() {
    zext_ln15_fu_354_p1 = esl_zext<64,5>(weights_V_offset.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_zext_ln42_1_fu_415_p1() {
    zext_ln42_1_fu_415_p1 = esl_zext<64,4>(add_ln42_1_fu_410_p2.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_zext_ln42_2_fu_425_p1() {
    zext_ln42_2_fu_425_p1 = esl_zext<64,4>(add_ln42_2_fu_420_p2.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_zext_ln42_3_fu_471_p1() {
    zext_ln42_3_fu_471_p1 = esl_zext<64,4>(add_ln42_3_fu_466_p2.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_zext_ln42_4_fu_481_p1() {
    zext_ln42_4_fu_481_p1 = esl_zext<64,4>(add_ln42_4_fu_476_p2.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_zext_ln42_5_fu_531_p1() {
    zext_ln42_5_fu_531_p1 = esl_zext<64,4>(add_ln42_5_fu_526_p2.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_zext_ln42_6_fu_541_p1() {
    zext_ln42_6_fu_541_p1 = esl_zext<64,4>(add_ln42_6_fu_536_p2.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_zext_ln42_fu_369_p1() {
    zext_ln42_fu_369_p1 = esl_zext<64,4>(add_ln42_fu_363_p2.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config3_1_s::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_reset_idle_pp0.read(), ap_const_logic_0) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_idle_pp0_1to1.read())))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            } else if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reset_idle_pp0.read()))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 2 : 
            if (esl_seteq<1,1,1>(ap_block_pp0_stage1_subdone.read(), ap_const_boolean_0)) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            }
            break;
        case 4 : 
            if (esl_seteq<1,1,1>(ap_block_pp0_stage2_subdone.read(), ap_const_boolean_0)) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            }
            break;
        case 8 : 
            if (esl_seteq<1,1,1>(ap_block_pp0_stage3_subdone.read(), ap_const_boolean_0)) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            }
            break;
        default : 
            ap_NS_fsm = "XXXX";
            break;
    }
}

}

