// ==============================================================
// Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2023.2 (64-bit)
// Tool Version Limit: 2023.10
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// 
// ==============================================================

extern "C" void AESL_WRAP_myproject (
volatile void* input_1,
volatile void* input_2,
volatile void* layer3_out_0,
volatile void* layer3_out_1,
volatile void* layer3_out_2,
volatile void* layer3_out_3,
volatile void* layer3_out_4,
volatile void* layer3_out_5,
volatile void* layer3_out_6,
volatile void* layer3_out_7,
volatile void* layer3_out_8,
volatile void* layer3_out_9,
volatile void* layer3_out_10,
volatile void* layer3_out_11,
volatile void* layer3_out_12,
volatile void* layer3_out_13,
volatile void* layer3_out_14,
volatile void* layer3_out_15,
volatile void* layer3_out_16,
volatile void* layer3_out_17,
volatile void* layer3_out_18,
volatile void* layer3_out_19,
volatile void* layer3_out_20,
volatile void* layer3_out_21,
volatile void* layer3_out_22,
volatile void* layer3_out_23,
volatile void* layer3_out_24,
volatile void* layer3_out_25,
volatile void* layer3_out_26,
volatile void* layer3_out_27,
volatile void* layer3_out_28,
volatile void* layer3_out_29,
volatile void* layer3_out_30,
volatile void* layer3_out_31,
volatile void* layer3_out_32,
volatile void* layer3_out_33,
volatile void* layer3_out_34,
volatile void* layer3_out_35,
volatile void* layer3_out_36,
volatile void* layer3_out_37,
volatile void* layer3_out_38,
volatile void* layer3_out_39,
volatile void* layer3_out_40,
volatile void* layer3_out_41,
volatile void* layer3_out_42,
volatile void* layer3_out_43,
volatile void* layer3_out_44,
volatile void* layer3_out_45,
volatile void* layer3_out_46,
volatile void* layer3_out_47,
volatile void* layer3_out_48,
volatile void* layer3_out_49,
volatile void* layer3_out_50,
volatile void* layer3_out_51,
volatile void* layer3_out_52,
volatile void* layer3_out_53,
volatile void* layer3_out_54,
volatile void* layer3_out_55,
volatile void* layer3_out_56,
volatile void* layer3_out_57,
volatile void* layer3_out_58,
volatile void* layer3_out_59,
volatile void* layer3_out_60,
volatile void* layer3_out_61,
volatile void* layer3_out_62,
volatile void* layer3_out_63,
volatile void* layer3_out_64,
volatile void* layer3_out_65,
volatile void* layer3_out_66,
volatile void* layer3_out_67,
volatile void* layer3_out_68,
volatile void* layer3_out_69,
volatile void* layer3_out_70,
volatile void* layer3_out_71,
volatile void* layer3_out_72,
volatile void* layer3_out_73,
volatile void* layer3_out_74,
volatile void* layer3_out_75,
volatile void* layer3_out_76,
volatile void* layer3_out_77,
volatile void* layer3_out_78,
volatile void* layer3_out_79);
