set ModuleHierarchy {[{
"Name" : "myproject","ID" : "0","Type" : "sequential",
"SubInsts" : [
	{"Name" : "grp_multiheadattention_ap_fixed_ap_fixed_config3_s_fu_206","ID" : "1","Type" : "dataflow",
		"SubInsts" : [
		{"Name" : "data_prep_ap_fixed_ap_fixed_16_6_5_3_0_config3_3_U0","ID" : "2","Type" : "sequential"},
		{"Name" : "data_prep_ap_fixed_ap_fixed_16_6_5_3_0_config3_2_U0","ID" : "3","Type" : "sequential"},
		{"Name" : "data_prep_ap_fixed_ap_fixed_16_6_5_3_0_config3_1_U0","ID" : "4","Type" : "sequential"},
		{"Name" : "data_prep_ap_fixed_ap_fixed_16_6_5_3_0_config3_U0","ID" : "5","Type" : "sequential"},
		{"Name" : "lin_projection_ap_fixed_ap_fixed_16_6_5_3_0_config3_1_U0","ID" : "6","Type" : "sequential",
			"SubInsts" : [
			{"Name" : "grp_read_stream_array_ap_fixed_16_6_5_3_0_4_s_fu_73","ID" : "7","Type" : "sequential"},
			{"Name" : "grp_read_stream_array_ap_fixed_16_6_5_3_0_4_s_fu_85","ID" : "8","Type" : "sequential"},
			{"Name" : "grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config3_1_2_fu_97","ID" : "9","Type" : "pipeline"},
			{"Name" : "grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config3_1_1_fu_109","ID" : "10","Type" : "pipeline"},
			{"Name" : "grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config3_1_s_fu_121","ID" : "11","Type" : "pipeline"},]},
		{"Name" : "lin_projection_ap_fixed_ap_fixed_16_6_5_3_0_config3_U0","ID" : "12","Type" : "sequential",
			"SubInsts" : [
			{"Name" : "grp_read_stream_array_ap_fixed_16_6_5_3_0_4_s_fu_73","ID" : "13","Type" : "sequential"},
			{"Name" : "grp_read_stream_array_ap_fixed_16_6_5_3_0_4_s_fu_85","ID" : "14","Type" : "sequential"},
			{"Name" : "grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config3_1_2_fu_97","ID" : "15","Type" : "pipeline"},
			{"Name" : "grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config3_1_1_fu_109","ID" : "16","Type" : "pipeline"},
			{"Name" : "grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config3_1_s_fu_121","ID" : "17","Type" : "pipeline"},]},
		{"Name" : "matrixmul_transpose_ap_fixed_ap_fixed_config3_1_U0","ID" : "18","Type" : "sequential",
			"SubInsts" : [
			{"Name" : "grp_softmax_legacy_ap_fixed_ap_fixed_softmax_config3_s_fu_50","ID" : "19","Type" : "pipeline"},
			{"Name" : "grp_softmax_legacy_ap_fixed_ap_fixed_softmax_config3_s_fu_78","ID" : "20","Type" : "pipeline"},
			{"Name" : "grp_softmax_legacy_ap_fixed_ap_fixed_softmax_config3_s_fu_106","ID" : "21","Type" : "pipeline"},
			{"Name" : "grp_softmax_legacy_ap_fixed_ap_fixed_softmax_config3_s_fu_134","ID" : "22","Type" : "pipeline"},
			{"Name" : "grp_softmax_legacy_ap_fixed_ap_fixed_softmax_config3_s_fu_162","ID" : "23","Type" : "pipeline"},
			{"Name" : "grp_softmax_legacy_ap_fixed_ap_fixed_softmax_config3_s_fu_190","ID" : "24","Type" : "pipeline"},
			{"Name" : "grp_softmax_legacy_ap_fixed_ap_fixed_softmax_config3_s_fu_218","ID" : "25","Type" : "pipeline"},
			{"Name" : "grp_softmax_legacy_ap_fixed_ap_fixed_softmax_config3_s_fu_246","ID" : "26","Type" : "pipeline"},
			{"Name" : "grp_softmax_legacy_ap_fixed_ap_fixed_softmax_config3_s_fu_274","ID" : "27","Type" : "pipeline"},
			{"Name" : "grp_softmax_legacy_ap_fixed_ap_fixed_softmax_config3_s_fu_302","ID" : "28","Type" : "pipeline"},
			{"Name" : "grp_softmax_legacy_ap_fixed_ap_fixed_softmax_config3_s_fu_330","ID" : "29","Type" : "pipeline"},
			{"Name" : "grp_softmax_legacy_ap_fixed_ap_fixed_softmax_config3_s_fu_358","ID" : "30","Type" : "pipeline"},
			{"Name" : "grp_softmax_legacy_ap_fixed_ap_fixed_softmax_config3_s_fu_386","ID" : "31","Type" : "pipeline"},
			{"Name" : "grp_softmax_legacy_ap_fixed_ap_fixed_softmax_config3_s_fu_414","ID" : "32","Type" : "pipeline"},
			{"Name" : "grp_softmax_legacy_ap_fixed_ap_fixed_softmax_config3_s_fu_442","ID" : "33","Type" : "pipeline"},
			{"Name" : "grp_softmax_legacy_ap_fixed_ap_fixed_softmax_config3_s_fu_470","ID" : "34","Type" : "pipeline"},
			{"Name" : "grp_softmax_legacy_ap_fixed_ap_fixed_softmax_config3_s_fu_498","ID" : "35","Type" : "pipeline"},
			{"Name" : "grp_softmax_legacy_ap_fixed_ap_fixed_softmax_config3_s_fu_526","ID" : "36","Type" : "pipeline"},
			{"Name" : "grp_softmax_legacy_ap_fixed_ap_fixed_softmax_config3_s_fu_554","ID" : "37","Type" : "pipeline"},
			{"Name" : "grp_softmax_legacy_ap_fixed_ap_fixed_softmax_config3_s_fu_582","ID" : "38","Type" : "pipeline"},]},
		{"Name" : "matrixmul_transpose_ap_fixed_ap_fixed_config3_U0","ID" : "39","Type" : "sequential",
			"SubInsts" : [
			{"Name" : "grp_softmax_legacy_ap_fixed_ap_fixed_softmax_config3_s_fu_50","ID" : "40","Type" : "pipeline"},
			{"Name" : "grp_softmax_legacy_ap_fixed_ap_fixed_softmax_config3_s_fu_78","ID" : "41","Type" : "pipeline"},
			{"Name" : "grp_softmax_legacy_ap_fixed_ap_fixed_softmax_config3_s_fu_106","ID" : "42","Type" : "pipeline"},
			{"Name" : "grp_softmax_legacy_ap_fixed_ap_fixed_softmax_config3_s_fu_134","ID" : "43","Type" : "pipeline"},
			{"Name" : "grp_softmax_legacy_ap_fixed_ap_fixed_softmax_config3_s_fu_162","ID" : "44","Type" : "pipeline"},
			{"Name" : "grp_softmax_legacy_ap_fixed_ap_fixed_softmax_config3_s_fu_190","ID" : "45","Type" : "pipeline"},
			{"Name" : "grp_softmax_legacy_ap_fixed_ap_fixed_softmax_config3_s_fu_218","ID" : "46","Type" : "pipeline"},
			{"Name" : "grp_softmax_legacy_ap_fixed_ap_fixed_softmax_config3_s_fu_246","ID" : "47","Type" : "pipeline"},
			{"Name" : "grp_softmax_legacy_ap_fixed_ap_fixed_softmax_config3_s_fu_274","ID" : "48","Type" : "pipeline"},
			{"Name" : "grp_softmax_legacy_ap_fixed_ap_fixed_softmax_config3_s_fu_302","ID" : "49","Type" : "pipeline"},
			{"Name" : "grp_softmax_legacy_ap_fixed_ap_fixed_softmax_config3_s_fu_330","ID" : "50","Type" : "pipeline"},
			{"Name" : "grp_softmax_legacy_ap_fixed_ap_fixed_softmax_config3_s_fu_358","ID" : "51","Type" : "pipeline"},
			{"Name" : "grp_softmax_legacy_ap_fixed_ap_fixed_softmax_config3_s_fu_386","ID" : "52","Type" : "pipeline"},
			{"Name" : "grp_softmax_legacy_ap_fixed_ap_fixed_softmax_config3_s_fu_414","ID" : "53","Type" : "pipeline"},
			{"Name" : "grp_softmax_legacy_ap_fixed_ap_fixed_softmax_config3_s_fu_442","ID" : "54","Type" : "pipeline"},
			{"Name" : "grp_softmax_legacy_ap_fixed_ap_fixed_softmax_config3_s_fu_470","ID" : "55","Type" : "pipeline"},
			{"Name" : "grp_softmax_legacy_ap_fixed_ap_fixed_softmax_config3_s_fu_498","ID" : "56","Type" : "pipeline"},
			{"Name" : "grp_softmax_legacy_ap_fixed_ap_fixed_softmax_config3_s_fu_526","ID" : "57","Type" : "pipeline"},
			{"Name" : "grp_softmax_legacy_ap_fixed_ap_fixed_softmax_config3_s_fu_554","ID" : "58","Type" : "pipeline"},
			{"Name" : "grp_softmax_legacy_ap_fixed_ap_fixed_softmax_config3_s_fu_582","ID" : "59","Type" : "pipeline"},]},
		{"Name" : "matrixmul_ap_fixed_ap_fixed_16_6_5_3_0_config3_1_U0","ID" : "60","Type" : "sequential"},
		{"Name" : "matrixmul_ap_fixed_ap_fixed_16_6_5_3_0_config3_U0","ID" : "61","Type" : "sequential"},
		{"Name" : "dense_out_ap_fixed_ap_fixed_16_6_5_3_0_config3_U0","ID" : "62","Type" : "sequential",
			"SubInsts" : [
			{"Name" : "grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config3_2_s_fu_768","ID" : "63","Type" : "pipeline"},]},]},]
}]}